#!/usr/bin/env python
"""Sanas: extract a smoke-test subset of the beintelli_v1 in-cabin dataset.

CPU only. Needs internet. Does NOT download the 73.5 GB archive: it reads the
ZIP central directory over HTTP range requests, selects the members it wants,
and pulls only those byte ranges from the HuggingFace mirror.

Default selection (~0.68 GB): front_left_color at stride 10, the matching
depth frames, and every annotation needed for counting.

Outputs, under /kaggle/working/subset (or ./data/subset locally):
  labels.jsonl   one row per frame: timestamp, image, sequence id,
                 count_view, count_cabin
  manifest.json  what was selected, what was transferred, count distributions

The frame selection lives in src/sanas/selection.py and is shared with the
depth kernels, so every run picks frames the same way.

DO NOT EDIT the generated block below. Edit src/sanas/ and run
`python scripts/build_kernels.py`.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time

# >>> SANAS-VENDOR: ziprange, selection, labels
# GENERATED by scripts/build_kernels.py from src/sanas/ - do not edit here.
# Edit the module in src/sanas/, then re-run the generator.

# ---- src/sanas/ziprange.py ----------------------------------------
import json
import os
import struct
import sys
import time
import urllib.error
import urllib.request
import zlib
from dataclasses import asdict, dataclass

MIRRORS = {
    "hf": (
        "https://huggingface.co/datasets/evgenygorelik96/"
        "multiview_incabin_dataset/resolve/main/beintelli_v1.zip"
    ),
    "zenodo": "https://zenodo.org/api/records/20559664/files/beintelli_v1.zip/content",
}
DEFAULT_MIRROR = "hf"

ARCHIVE_NAME = "beintelli_v1.zip"
ARCHIVE_SIZE = 73_515_214_805
ARCHIVE_MD5 = "74924b5be59e706a5a89affba48f6b87"
ROOT_PREFIX = "beintelli_v1/"

# A local file header is 30 bytes + filename + extra field. The central
# directory does not record the *local* extra length, so a run's end is an
# estimate. Padding by the legal maximum (65535) would waste ~25% of the
# transfer on a stride-10 selection, so pad small and let the reader re-fetch
# exactly when a member turns out to overrun its run. Observed local extra
# length in this archive is 32 bytes.
_LOCAL_EXTRA_PAD = 1024

_USER_AGENT = "sanas-occupancy/0.1 (+research; contact via project repo)"


# --------------------------------------------------------------------------
# HTTP
# --------------------------------------------------------------------------


def http_get(
    url: str,
    start: int | None = None,
    end: int | None = None,
    retries: int = 5,
    timeout: int = 120,
    backoff: float = 2.0,
) -> bytes:
    """GET url, optionally a byte range (inclusive bounds), with retries."""
    headers = {"User-Agent": _USER_AGENT}
    if start is not None:
        headers["Range"] = f"bytes={start}-{'' if end is None else end}"
    last: Exception | None = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                if start is not None and resp.status != 206:
                    raise OSError(
                        f"server ignored Range (status {resp.status}); "
                        "mirror does not support partial download"
                    )
                return resp.read()
        except Exception as exc:  # noqa: BLE001 - retry on anything transient
            last = exc
            if attempt == retries - 1:
                break
            time.sleep(backoff**attempt)
    raise OSError(f"GET failed after {retries} attempts: {url} ({last})")


def remote_size(url: str, timeout: int = 60) -> int:
    """Content-Length of the remote archive."""
    req = urllib.request.Request(
        url, method="HEAD", headers={"User-Agent": _USER_AGENT}
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return int(resp.headers["Content-Length"])


# --------------------------------------------------------------------------
# Central directory
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Member:
    """One entry of the ZIP central directory."""

    name: str
    method: int  # 0 = stored, 8 = deflate
    size: int  # uncompressed
    csize: int  # compressed
    offset: int  # local header offset
    crc: int

    @property
    def is_dir(self) -> bool:
        return self.name.endswith("/")


def _find_eocd(tail: bytes) -> tuple[int, int, int]:
    """Return (entry_count, cd_size, cd_offset) from the ZIP tail."""
    i = tail.rfind(b"PK\x05\x06")
    if i == -1:
        raise ValueError("end-of-central-directory record not found in tail")
    _, _, _, _, n, cd_size, cd_off, _ = struct.unpack("<IHHHHIIH", tail[i : i + 22])

    j = tail.rfind(b"PK\x06\x06")
    if j != -1:
        z = struct.unpack("<IQHHIIQQQQ", tail[j : j + 56])
        n, cd_size, cd_off = z[7], z[8], z[9]
    if cd_off == 0xFFFFFFFF:
        raise ValueError("ZIP64 locator required but not found")
    return n, cd_size, cd_off


def parse_central_directory(blob: bytes) -> list[Member]:
    """Parse a raw central directory into Member records (ZIP64 aware)."""
    members: list[Member] = []
    off = 0
    end = len(blob)
    while off + 46 <= end:
        if blob[off : off + 4] != b"PK\x01\x02":
            break
        (
            _sig,
            _vmb,
            _vnb,
            _flags,
            method,
            _mtime,
            _mdate,
            crc,
            csize,
            usize,
            nlen,
            elen,
            clen,
            _dstart,
            _iattr,
            _eattr,
            lhoff,
        ) = struct.unpack("<IHHHHHHIIIHHHHHII", blob[off : off + 46])

        name = blob[off + 46 : off + 46 + nlen].decode("utf-8", "replace")
        extra = blob[off + 46 + nlen : off + 46 + nlen + elen]

        # ZIP64 extended information overrides the 0xFFFFFFFF sentinels.
        eo = 0
        while eo + 4 <= len(extra):
            hid, hsz = struct.unpack("<HH", extra[eo : eo + 4])
            body = extra[eo + 4 : eo + 4 + hsz]
            if hid == 0x0001:
                bo = 0
                if usize == 0xFFFFFFFF and bo + 8 <= len(body):
                    usize = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
                if csize == 0xFFFFFFFF and bo + 8 <= len(body):
                    csize = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
                if lhoff == 0xFFFFFFFF and bo + 8 <= len(body):
                    lhoff = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
            eo += 4 + hsz

        members.append(Member(name, method, usize, csize, lhoff, crc))
        off += 46 + nlen + elen + clen
    return members


def read_members(url: str, verbose: bool = True) -> tuple[int, list[Member]]:
    """Fetch and parse the central directory. Downloads ~45 MB, not the archive.

    Returns (archive_size, members). This is the form the kernels use;
    build_index() wraps it for the on-disk index artifact.
    """
    total = remote_size(url)
    if verbose:
        print(f"archive size: {total:,} bytes", flush=True)

    tail = http_get(url, total - 65_536, total - 1)
    n_entries, cd_size, cd_off = _find_eocd(tail)
    if verbose:
        print(
            f"central directory: {n_entries:,} entries, "
            f"{cd_size:,} bytes at offset {cd_off:,}",
            flush=True,
        )

    blob = http_get(url, cd_off, cd_off + cd_size - 1)
    members = parse_central_directory(blob)
    if len(members) != n_entries:
        print(
            f"WARNING: parsed {len(members)} entries, EOCD claims {n_entries}",
            file=sys.stderr,
        )

    return total, members


def build_index(url: str, verbose: bool = True) -> dict:
    """Serialisable index for the on-disk artifact (scripts/build_zip_index.py)."""
    total, members = read_members(url, verbose=verbose)
    return {
        "archive": ARCHIVE_NAME,
        "archive_size": total,
        "archive_md5": ARCHIVE_MD5 if total == ARCHIVE_SIZE else None,
        "source_url": url,
        "entry_count": len(members),
        "members": [asdict(m) for m in members],
    }


def save_index(path: str, index: dict) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(index, fh)


def load_index(path: str) -> tuple[dict, list[Member]]:
    with open(path, encoding="utf-8") as fh:
        index = json.load(fh)
    return index, [Member(**m) for m in index["members"]]


# --------------------------------------------------------------------------
# Extraction
# --------------------------------------------------------------------------


def sniff_image_ext(data: bytes) -> str | None:
    """Return the real extension for an image payload, or None if unknown.

    The dataset's depth frames are named ``*.jpg`` but are actually PNG
    (magic 89 50 4E 47). Anything decoding by extension will mislabel them.
    """
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return ".png"
    if data[:2] == b"\xff\xd8":
        return ".jpg"
    return None


def _run_end(member: Member, archive_size: int) -> int:
    """Exclusive upper bound on the bytes a member can occupy."""
    return min(
        archive_size,
        member.offset
        + 30
        + len(member.name.encode())
        + _LOCAL_EXTRA_PAD
        + member.csize,
    )


def plan_runs(
    members: list[Member],
    archive_size: int,
    gap_merge: int = 1 << 20,
    max_run_bytes: int = 256 << 20,
) -> list[tuple[int, int, list[Member]]]:
    """Group members into contiguous byte runs to keep the request count sane.

    Fetching 130k tiny annotation files one request each is not viable; the
    annotation directories are physically contiguous at the end of the archive
    so they collapse into a handful of runs.
    """
    ordered = sorted((m for m in members if not m.is_dir), key=lambda m: m.offset)
    runs: list[tuple[int, int, list[Member]]] = []
    for m in ordered:
        m_end = _run_end(m, archive_size)
        if runs:
            start, end, group = runs[-1]
            if m.offset - end <= gap_merge and (m_end - start) <= max_run_bytes:
                group.append(m)
                runs[-1] = (start, max(end, m_end), group)
                continue
        runs.append((m.offset, m_end, [m]))
    return runs


def _member_data(buf: bytes, member: Member, base: int, url: str) -> tuple[bytes, int]:
    """Slice one member out of a run buffer and decompress it.

    Falls back to an exact range request for whatever the run buffer did not
    cover, so the run-end estimate never has to be conservative. Returns
    (data, extra_requests).
    """
    extra = 0
    pos = member.offset - base
    if pos < 0 or pos + 30 > len(buf):
        header = http_get(url, member.offset, member.offset + 29)
        extra += 1
    else:
        header = buf[pos : pos + 30]

    sig, _ver, _flg, _meth, _t, _d, _crc, _c, _u, nlen, elen = struct.unpack(
        "<IHHHHHIIIHH", header
    )
    if sig != 0x04034B50:
        raise ValueError(f"bad local header signature for {member.name}")

    data_start = member.offset + 30 + nlen + elen
    lo = data_start - base
    if lo >= 0 and lo + member.csize <= len(buf):
        raw = buf[lo : lo + member.csize]
    else:
        raw = http_get(url, data_start, data_start + member.csize - 1)
        extra += 1
    if len(raw) != member.csize:
        raise ValueError(f"short read for {member.name}")

    data = zlib.decompress(raw, -15) if member.method == 8 else raw
    if member.crc and zlib.crc32(data) & 0xFFFFFFFF != member.crc:
        raise ValueError(f"CRC mismatch for {member.name}")
    return data, extra


def extract_members(
    url: str,
    members: list[Member],
    out_dir: str,
    archive_size: int = ARCHIVE_SIZE,
    strip_prefix: str = ROOT_PREFIX,
    gap_merge: int = 1 << 20,
    max_run_bytes: int = 256 << 20,
    fix_image_extensions: bool = True,
    verbose: bool = True,
) -> dict:
    """Download and inflate the given members into out_dir.

    Returns a summary dict. Members are written at their archive-relative
    path with ``strip_prefix`` removed. When ``fix_image_extensions`` is set,
    a file whose payload disagrees with its extension is written with the
    correct one (this is what handles the depth-frames-are-PNG problem).
    """
    runs = plan_runs(members, archive_size, gap_merge, max_run_bytes)
    planned = sum(end - start for start, end, _ in runs)
    if verbose:
        print(
            f"extracting {len(members):,} members in {len(runs):,} range request(s); "
            f"~{planned / 1e9:.3f} GB to transfer",
            flush=True,
        )

    written = 0
    bytes_out = 0
    extra_requests = 0
    renamed: list[tuple[str, str]] = []
    t0 = time.time()

    for idx, (start, end, group) in enumerate(runs, 1):
        buf = http_get(url, start, end - 1)
        for m in group:
            data, extra = _member_data(buf, m, start, url)
            extra_requests += extra
            rel = (
                m.name[len(strip_prefix) :]
                if m.name.startswith(strip_prefix)
                else m.name
            )
            if fix_image_extensions:
                stem, ext = os.path.splitext(rel)
                real = sniff_image_ext(data[:8])
                if (
                    real
                    and ext.lower() in {".jpg", ".jpeg", ".png"}
                    and real != ext.lower()
                ):
                    renamed.append((rel, stem + real))
                    rel = stem + real
            dst = os.path.join(out_dir, rel.replace("/", os.sep))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            with open(dst, "wb") as fh:
                fh.write(data)
            written += 1
            bytes_out += len(data)
        if verbose and (idx % 25 == 0 or idx == len(runs)):
            rate = planned / max(time.time() - t0, 1e-6) / 1e6
            print(
                f"  run {idx}/{len(runs)}  files={written:,}  "
                f"out={bytes_out / 1e9:.3f} GB  ~{rate:.1f} MB/s",
                flush=True,
            )

    if renamed and verbose:
        print(
            f"  corrected {len(renamed)} file extension(s) after magic-byte sniff "
            f"(e.g. {renamed[0][0]} -> {renamed[0][1]})",
            flush=True,
        )

    return {
        "members": written,
        "bytes_written": bytes_out,
        "bytes_transferred_planned": planned,
        "runs": len(runs),
        "extra_requests": extra_requests,
        "renamed": renamed[:50],
        "renamed_total": len(renamed),
        "seconds": round(time.time() - t0, 1),
    }

# ---- src/sanas/selection.py ---------------------------------------
import bisect
import os
from dataclasses import dataclass, field

ROOT_PREFIX = "beintelli_v1/"

ROOT_METADATA = {
    ROOT_PREFIX + "person_states.json",
    ROOT_PREFIX + "modalities.json",
    ROOT_PREFIX + "frame_ids.json",
    ROOT_PREFIX + "target_transforms.json",
}

COLOR_CAMERAS = [
    "front_left_color",
    "front_right_color",
    "center_left_color",
    "back_right_color",
]

NS_PER_MS = 1_000_000

# What the already-executed single-camera extraction produced. Any change to
# selection logic that moves these numbers is drift and must be deliberate.
SINGLE_CAMERA_EXPECTATION = {
    "images": 1289,
    "depth": 1204,
    "labels": 32911,
    "total_members": 35404,
}


@dataclass
class SubsetSpec:
    """Which archive members a run wants."""

    color_cameras: list = field(default_factory=lambda: ["front_left_color"])
    # Depth streams to pull. None -> the depth twin of each colour camera.
    depth_cameras: list | None = None
    # Colour camera whose frame times define the sampling grid. All depth
    # streams are matched to these instants so the cameras stay in sync.
    timebase_camera: str | None = None
    stride: int = 10
    max_images: int = 0
    include_depth: bool = True
    include_masks: bool = False
    include_poses: bool = False
    depth_tolerance_ms: int = 100

    def resolved_depth_cameras(self) -> list:
        if self.depth_cameras is not None:
            return list(self.depth_cameras)
        if not self.include_depth:
            return []
        return [c.replace("_color", "_depth") for c in self.color_cameras]

    def resolved_timebase(self) -> str:
        return self.timebase_camera or self.color_cameras[0]


def timestamp_of(name: str) -> int | None:
    """19-digit nanosecond stamp from a member name, or None."""
    stem = os.path.splitext(os.path.basename(name))[0].split("_")[0]
    return int(stem) if stem.isdigit() and len(stem) == 19 else None


def nearest(ts: int, sorted_ts: list, tolerance_ns: int) -> int | None:
    if not sorted_ts:
        return None
    i = bisect.bisect_left(sorted_ts, ts)
    best = None
    for j in (i - 1, i):
        if 0 <= j < len(sorted_ts):
            d = abs(sorted_ts[j] - ts)
            if d <= tolerance_ns and (best is None or d < abs(best - ts)):
                best = sorted_ts[j]
    return best


def select_members(members, spec: SubsetSpec):
    """Return (selected_members, breakdown_dict) for a SubsetSpec."""
    timebase = spec.resolved_timebase()
    depth_cams = spec.resolved_depth_cameras()

    # ---- colour frames -------------------------------------------------
    images = []
    per_camera_images = {}
    for cam in spec.color_cameras:
        cam_imgs = sorted(
            (
                m
                for m in members
                if m.name.startswith(f"{ROOT_PREFIX}cameras/color/{cam}/images/")
                and m.name.endswith(".jpg")
            ),
            key=lambda m: m.name,
        )
        picked = cam_imgs[:: spec.stride]
        if spec.max_images:
            picked = picked[: spec.max_images]
        per_camera_images[cam] = picked
        images.extend(picked)

    timebase_ts = [timestamp_of(m.name) for m in per_camera_images.get(timebase, [])]
    timebase_ts = [t for t in timebase_ts if t is not None]

    # ---- annotations ---------------------------------------------------
    seg_prefixes = tuple(f"{ROOT_PREFIX}segmentations/{c}/" for c in spec.color_cameras)
    labels = []
    for m in members:
        n = m.name
        if m.is_dir:
            continue
        if n.startswith(seg_prefixes):
            if n.endswith(".json") or (spec.include_masks and n.endswith(".png")):
                labels.append(m)
        elif n.startswith(f"{ROOT_PREFIX}bboxes_3d/") or n.startswith(
            f"{ROOT_PREFIX}states/"
        ):
            labels.append(m)
        elif spec.include_poses and n.startswith(f"{ROOT_PREFIX}poses/"):
            labels.append(m)
        elif n in ROOT_METADATA:
            labels.append(m)
        elif n.startswith(f"{ROOT_PREFIX}cameras/") and n.endswith("camera_info.yaml"):
            labels.append(m)

    # ---- depth frames, matched to the timebase -------------------------
    depth = []
    per_camera_depth = {}
    tol = spec.depth_tolerance_ms * NS_PER_MS
    for dcam in depth_cams:
        cand = {}
        for m in members:
            if m.is_dir:
                continue
            if not m.name.startswith(f"{ROOT_PREFIX}cameras/depth/{dcam}/images/"):
                continue
            t = timestamp_of(m.name)
            if t is not None:
                cand[t] = m
        keys = sorted(cand)
        seen, chosen = set(), []
        for t in timebase_ts:
            hit = nearest(t, keys, tol)
            if hit is not None and hit not in seen:
                seen.add(hit)
                chosen.append(cand[hit])
        per_camera_depth[dcam] = chosen
        depth.extend(chosen)

    selected = images + labels + depth
    breakdown = {
        "timebase_camera": timebase,
        "stride": spec.stride,
        "images": len(images),
        "image_bytes": sum(m.csize for m in images),
        "labels": len(labels),
        "label_bytes": sum(m.csize for m in labels),
        "depth": len(depth),
        "depth_bytes": sum(m.csize for m in depth),
        "total_members": len(selected),
        "total_compressed_bytes": sum(m.csize for m in selected),
        "per_camera_images": {c: len(v) for c, v in per_camera_images.items()},
        "per_camera_depth": {c: len(v) for c, v in per_camera_depth.items()},
        "per_camera_depth_bytes": {
            c: sum(m.csize for m in v) for c, v in per_camera_depth.items()
        },
    }
    return selected, breakdown


def check_single_camera_regression(breakdown: dict, keys=None) -> list:
    """Compare a single-camera breakdown against what already ran.

    `keys` limits the comparison, because a run that deliberately skips depth
    cannot be expected to match the depth-inclusive frame counts. Returns a
    list of human-readable mismatches; empty means no drift.
    """
    problems = []
    for key, expected in SINGLE_CAMERA_EXPECTATION.items():
        if keys is not None and key not in keys:
            continue
        actual = breakdown.get(key)
        if actual != expected:
            problems.append(f"{key}: expected {expected:,}, got {actual:,}")
    return problems

# ---- src/sanas/labels.py ------------------------------------------
import bisect
import json
import os

NS_PER_MS = 1_000_000


def counts_from_segmentation(
    payload: bytes | str, score_threshold: float = 0.0
) -> tuple[int, float | None]:
    """Return (person_count, min_score) for one segmentation JSON."""
    entries = json.loads(payload)
    if not isinstance(entries, list):
        raise ValueError("segmentation JSON is not a list")
    kept = [e for e in entries if float(e.get("score", 1.0)) >= score_threshold]
    min_score = min((float(e.get("score", 1.0)) for e in kept), default=None)
    return len(kept), min_score


def counts_from_bboxes(payload: bytes | str, label: str = "human") -> int:
    """Return the number of oriented 3D boxes with the given label."""
    entries = json.loads(payload)
    if not isinstance(entries, list):
        raise ValueError("bboxes_3d JSON is not a list")
    return sum(1 for e in entries if e.get("bbox_label") == label)


def _ts_from_filename(path: str) -> int | None:
    stem = os.path.splitext(os.path.basename(path))[0]
    stem = stem.split("_")[0]
    return int(stem) if stem.isdigit() and len(stem) == 19 else None


def load_view_counts(
    subset_dir: str, camera: str, score_threshold: float = 0.0
) -> dict[int, tuple[int, float | None]]:
    """Map camera timestamp -> (count_view, min_score) for one camera."""
    seg_dir = os.path.join(subset_dir, "segmentations", camera)
    out: dict[int, tuple[int, float | None]] = {}
    if not os.path.isdir(seg_dir):
        return out
    for name in os.listdir(seg_dir):
        if not name.endswith(".json"):
            continue
        ts = _ts_from_filename(name)
        if ts is None:
            continue
        with open(os.path.join(seg_dir, name), "rb") as fh:
            out[ts] = counts_from_segmentation(fh.read(), score_threshold)
    return out


def load_cabin_counts(subset_dir: str) -> dict[int, int]:
    """Map lidar timestamp -> total occupants from bboxes_3d."""
    box_dir = os.path.join(subset_dir, "bboxes_3d")
    out: dict[int, int] = {}
    if not os.path.isdir(box_dir):
        return out
    for name in os.listdir(box_dir):
        if not name.endswith(".json"):
            continue
        ts = _ts_from_filename(name)
        if ts is None:
            continue
        with open(os.path.join(box_dir, name), "rb") as fh:
            out[ts] = counts_from_bboxes(fh.read())
    return out


def match_nearest(ts: int, sorted_ts: list[int], tolerance_ns: int) -> int | None:
    """Nearest timestamp in sorted_ts within tolerance, else None."""
    if not sorted_ts:
        return None
    i = bisect.bisect_left(sorted_ts, ts)
    best = None
    for j in (i - 1, i):
        if 0 <= j < len(sorted_ts):
            d = abs(sorted_ts[j] - ts)
            if d <= tolerance_ns and (best is None or d < abs(best - ts)):
                best = sorted_ts[j]
    return best


def assign_sequences(sorted_ts: list[int], gap_ns: int = 5 * 10**9) -> dict[int, int]:
    """Split a timestamp list into sub-sequences at recording gaps.

    Frames are ~0.067 s apart, so a random train/val split leaks near-duplicate
    neighbours across the boundary. The recording has 10 gaps > 5 s in
    front_left_color, giving 11 sub-sequences to split on instead.
    """
    seq: dict[int, int] = {}
    current = 0
    for i, ts in enumerate(sorted_ts):
        if i and ts - sorted_ts[i - 1] > gap_ns:
            current += 1
        seq[ts] = current
    return seq


def build_label_table(
    subset_dir: str,
    camera: str,
    score_threshold: float = 0.0,
    cabin_tolerance_ns: int = 100 * NS_PER_MS,
    sequence_gap_ns: int = 5 * 10**9,
) -> list[dict]:
    """Join extracted images with their counts into one row per frame."""
    img_dir = os.path.join(subset_dir, "cameras", "color", camera, "images")
    if not os.path.isdir(img_dir):
        raise FileNotFoundError(f"no extracted images at {img_dir}")

    images: dict[int, str] = {}
    for name in sorted(os.listdir(img_dir)):
        ts = _ts_from_filename(name)
        if ts is not None:
            images[ts] = f"cameras/color/{camera}/images/{name}"

    view = load_view_counts(subset_dir, camera, score_threshold)
    cabin = load_cabin_counts(subset_dir)
    cabin_ts = sorted(cabin)

    ordered = sorted(images)
    seq = assign_sequences(ordered, sequence_gap_ns)

    rows: list[dict] = []
    for ts in ordered:
        v = view.get(ts)
        c_ts = match_nearest(ts, cabin_ts, cabin_tolerance_ns)
        rows.append(
            {
                "timestamp": ts,
                "camera": camera,
                "image": images[ts],
                "sequence": seq[ts],
                "count_view": None if v is None else v[0],
                "min_score": None if v is None else v[1],
                "count_cabin": None if c_ts is None else cabin[c_ts],
                "cabin_dt_ns": None if c_ts is None else c_ts - ts,
            }
        )
    return rows


def count_distribution(rows: list[dict], column: str) -> dict[str, int]:
    dist: dict[str, int] = {}
    for r in rows:
        key = "missing" if r.get(column) is None else str(r[column])
        dist[key] = dist.get(key, 0) + 1
    return dict(sorted(dist.items(), key=lambda kv: (kv[0] == "missing", kv[0])))


def write_labels(path: str, rows: list[dict]) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")


def read_labels(path: str) -> list[dict]:
    with open(path, encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]

# <<< SANAS-VENDOR


def default_out_dir() -> str:
    return (
        "/kaggle/working/subset"
        if os.path.isdir("/kaggle/working")
        else os.path.join("data", "subset")
    )


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Extract a smoke-test subset (HTTP range requests only)"
    )
    ap.add_argument("--mirror", choices=sorted(MIRRORS), default="hf")
    ap.add_argument("--camera", default="front_left_color")
    ap.add_argument(
        "--stride", type=int, default=10, help="take every Nth colour frame"
    )
    ap.add_argument("--max-images", type=int, default=0, help="0 = no cap")
    ap.add_argument("--out", default=None)
    ap.add_argument(
        "--score-threshold",
        type=float,
        default=0.0,
        help="drop pseudo-label detections below this score",
    )
    ap.add_argument("--cabin-tolerance-ms", type=int, default=100)
    ap.add_argument("--sequence-gap-s", type=int, default=5)
    ap.add_argument("--include-masks", action="store_true")
    ap.add_argument("--include-poses", action="store_true")
    ap.add_argument(
        "--include-depth",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="pull the depth frame matching each colour frame",
    )
    ap.add_argument("--depth-tolerance-ms", type=int, default=100)
    ap.add_argument(
        "--dry-run", action="store_true", help="report the selection, download nothing"
    )
    args = ap.parse_args()

    out_dir = args.out or default_out_dir()
    url = MIRRORS[args.mirror]
    t_start = time.time()

    print("=" * 72)
    print("Sanas subset extraction")
    print("=" * 72)
    print(f"mirror   : {args.mirror}")
    print(f"camera   : {args.camera}   stride: {args.stride}")
    print(f"out dir  : {out_dir}\n")

    archive_size, members = read_members(url)
    if archive_size != ARCHIVE_SIZE:
        print(
            f"WARNING: archive is {archive_size:,} bytes, expected {ARCHIVE_SIZE:,}. "
            "The mirror may have changed; re-verify before trusting results.",
            file=sys.stderr,
        )

    spec = SubsetSpec(
        color_cameras=[args.camera],
        timebase_camera=args.camera,
        stride=args.stride,
        max_images=args.max_images,
        include_depth=args.include_depth,
        include_masks=args.include_masks,
        include_poses=args.include_poses,
        depth_tolerance_ms=args.depth_tolerance_ms,
    )
    selected, breakdown = select_members(members, spec)

    print("selection:")
    for k in (
        "images",
        "image_bytes",
        "labels",
        "label_bytes",
        "depth",
        "depth_bytes",
        "total_members",
        "total_compressed_bytes",
    ):
        print(f"  {k:<26} {breakdown[k]:,}")
    print(
        f"  {'estimated transfer GB':<26} {breakdown['total_compressed_bytes'] / 1e9:.3f}"
    )

    if args.stride == 10 and args.max_images == 0 and args.camera == "front_left_color":
        problems = check_single_camera_regression(breakdown)
        print(
            "  regression vs executed run: "
            + ("CLEAN" if not problems else "DRIFT -> " + "; ".join(problems))
        )

    if not selected:
        print("nothing selected - check --camera", file=sys.stderr)
        return 1

    if args.dry_run:
        runs = plan_runs(selected, archive_size)
        planned = sum(e - s for s, e, _ in runs)
        print(
            f"\n--dry-run: would issue {len(runs):,} range request(s), "
            f"~{planned / 1e9:.3f} GB. Nothing downloaded."
        )
        return 0

    os.makedirs(out_dir, exist_ok=True)
    stats = extract_members(url, selected, out_dir, archive_size=archive_size)
    print(
        f"\nextracted {stats['members']:,} files, "
        f"{stats['bytes_written'] / 1e9:.3f} GB on disk in {stats['seconds']}s"
    )

    rows = build_label_table(
        out_dir,
        args.camera,
        score_threshold=args.score_threshold,
        cabin_tolerance_ns=args.cabin_tolerance_ms * NS_PER_MS,
        sequence_gap_ns=args.sequence_gap_s * 10**9,
    )
    labels_path = os.path.join(out_dir, "labels.jsonl")
    write_labels(labels_path, rows)

    dist_view = count_distribution(rows, "count_view")
    dist_cabin = count_distribution(rows, "count_cabin")
    seqs = sorted({r["sequence"] for r in rows})
    missing_view = sum(1 for r in rows if r["count_view"] is None)

    manifest = {
        "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "mirror": args.mirror,
        "source_url": url,
        "archive_size": archive_size,
        "archive_md5_expected": ARCHIVE_MD5,
        "camera": args.camera,
        "stride": args.stride,
        "score_threshold": args.score_threshold,
        "selection": breakdown,
        "transfer": stats,
        "frames": len(rows),
        "sequences": len(seqs),
        "frames_missing_view_label": missing_view,
        "count_view_distribution": dist_view,
        "count_cabin_distribution": dist_cabin,
        "labels_file": "labels.jsonl",
        "note": (
            "count_view = persons in this camera view (segmentation pseudo-labels). "
            "count_cabin = total cabin occupants (3D boxes, nearest lidar timestamp). "
            "Pseudo-labels, not human ground truth. Max 4 occupants anywhere in this "
            "dataset, single daytime session."
        ),
    }
    with open(os.path.join(out_dir, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)

    print("\n" + "=" * 72)
    print(f"frames                : {len(rows):,}")
    print(f"sub-sequences         : {len(seqs)}")
    print(f"missing view label    : {missing_view}")
    print(f"count_view  dist      : {dist_view}")
    print(f"count_cabin dist      : {dist_cabin}")
    print(f"labels                : {labels_path}")
    print(f"total wall clock      : {time.time() - t_start:.0f}s")
    print("=" * 72)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
