#!/usr/bin/env python
"""CANCELLED 2026-08-10 - INACTIVE, DO NOT PUSH. Kept in case safety work returns.

Cancelled because the product MVP deferred incident detection to a later
phase. Without safety features, covering the whole cabin with four sensors is
over-built; the MVP moved to a door-mounted 3D APC (the iris IRMA MATRIX /
INIT / Dilax pattern). This kernel was never pushed and never ran.

It is retained, not deleted: if the safety track comes back, cabin-wide
occupancy is the right shape for it, and the floor-coverage finding below is
the reason it would need more or better-placed sensors.

What it measured before cancellation (30-frame local sample, never a
sanctioned run): four cameras cover only 28.8% of the floor area occupants
actually use at the 0.3-3.0 m depth spec limit, and only 63.3% even at a
10 m gate. That gap is what made the cabin-wide design unattractive
independently of the MVP decision.

--------------------------------------------------------------------------
Sanas branch 2b: multi-zone occupancy from all four depth streams. CPU only.

SELF-CONTAINED, same pattern as the single-camera kernel: it fetches its own
subset from the HuggingFace mirror by HTTP range request, then scores.

This is NOT a fork of depth_occupancy.py. Both kernels inline the identical
generated block from src/sanas/ and differ only in the entry point below
(`default_mode="multi"` instead of "single"). That is deliberate: the whole
point of this kernel is a 1-camera vs 4-camera comparison, which is worthless
if the two paths are separate implementations that can drift apart.

What it does, in order:
  1. geometric floor coverage on empty-cabin frames, and STOPS if four
     cameras still leave occupied floor unseen
  2. merged BEV occupancy grid in base_link
  3. correlation against ground-truth counts, with bootstrap intervals
  4. head-to-head 1 camera vs 4 cameras
  5. an explicit statement of what this tests and what it does not

Fetch size: front_left colour at stride 10 as the timebase (0.335 GB) plus all
four depth streams matched to those instants (1.124 GB) plus annotations, so
about 1.47 GB selected per run. Depth frames are MATCHED to the colour
timebase rather than each stream being strided independently: four
independently strided streams would sample four different instants, and a
person who moves between them would land in four different places in the
merged grid.

DO NOT EDIT the generated block below. Edit src/sanas/ and run
`python scripts/build_kernels.py`.
"""

from __future__ import annotations

import argparse
import bisect
import json
import math
import os
import re
import struct
import sys
import time
import urllib.request
import zlib
from dataclasses import asdict, dataclass, field

import numpy as np

# >>> SANAS-VENDOR: ziprange, selection, labels, fetch, depth_occupancy, depth_kernel
# GENERATED by scripts/build_kernels.py from src/sanas/ - do not edit here.
# Edit the module in src/sanas/, then re-run the generator.

# ---- src/sanas/ziprange.py ----------------------------------------
import json
import os
import struct
import sys
import time
import urllib.error
import urllib.request
import zlib
from dataclasses import asdict, dataclass

MIRRORS = {
    "hf": (
        "https://huggingface.co/datasets/evgenygorelik96/"
        "multiview_incabin_dataset/resolve/main/beintelli_v1.zip"
    ),
    "zenodo": "https://zenodo.org/api/records/20559664/files/beintelli_v1.zip/content",
}
DEFAULT_MIRROR = "hf"

ARCHIVE_NAME = "beintelli_v1.zip"
ARCHIVE_SIZE = 73_515_214_805
ARCHIVE_MD5 = "74924b5be59e706a5a89affba48f6b87"
ROOT_PREFIX = "beintelli_v1/"

# A local file header is 30 bytes + filename + extra field. The central
# directory does not record the *local* extra length, so a run's end is an
# estimate. Padding by the legal maximum (65535) would waste ~25% of the
# transfer on a stride-10 selection, so pad small and let the reader re-fetch
# exactly when a member turns out to overrun its run. Observed local extra
# length in this archive is 32 bytes.
_LOCAL_EXTRA_PAD = 1024

_USER_AGENT = "sanas-occupancy/0.1 (+research; contact via project repo)"


# --------------------------------------------------------------------------
# HTTP
# --------------------------------------------------------------------------


def http_get(
    url: str,
    start: int | None = None,
    end: int | None = None,
    retries: int = 5,
    timeout: int = 120,
    backoff: float = 2.0,
) -> bytes:
    """GET url, optionally a byte range (inclusive bounds), with retries."""
    headers = {"User-Agent": _USER_AGENT}
    if start is not None:
        headers["Range"] = f"bytes={start}-{'' if end is None else end}"
    last: Exception | None = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                if start is not None and resp.status != 206:
                    raise OSError(
                        f"server ignored Range (status {resp.status}); "
                        "mirror does not support partial download"
                    )
                return resp.read()
        except Exception as exc:  # noqa: BLE001 - retry on anything transient
            last = exc
            if attempt == retries - 1:
                break
            time.sleep(backoff**attempt)
    raise OSError(f"GET failed after {retries} attempts: {url} ({last})")


def remote_size(url: str, timeout: int = 60) -> int:
    """Content-Length of the remote archive."""
    req = urllib.request.Request(
        url, method="HEAD", headers={"User-Agent": _USER_AGENT}
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return int(resp.headers["Content-Length"])


# --------------------------------------------------------------------------
# Central directory
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Member:
    """One entry of the ZIP central directory."""

    name: str
    method: int  # 0 = stored, 8 = deflate
    size: int  # uncompressed
    csize: int  # compressed
    offset: int  # local header offset
    crc: int

    @property
    def is_dir(self) -> bool:
        return self.name.endswith("/")


def _find_eocd(tail: bytes) -> tuple[int, int, int]:
    """Return (entry_count, cd_size, cd_offset) from the ZIP tail."""
    i = tail.rfind(b"PK\x05\x06")
    if i == -1:
        raise ValueError("end-of-central-directory record not found in tail")
    _, _, _, _, n, cd_size, cd_off, _ = struct.unpack("<IHHHHIIH", tail[i : i + 22])

    j = tail.rfind(b"PK\x06\x06")
    if j != -1:
        z = struct.unpack("<IQHHIIQQQQ", tail[j : j + 56])
        n, cd_size, cd_off = z[7], z[8], z[9]
    if cd_off == 0xFFFFFFFF:
        raise ValueError("ZIP64 locator required but not found")
    return n, cd_size, cd_off


def parse_central_directory(blob: bytes) -> list[Member]:
    """Parse a raw central directory into Member records (ZIP64 aware)."""
    members: list[Member] = []
    off = 0
    end = len(blob)
    while off + 46 <= end:
        if blob[off : off + 4] != b"PK\x01\x02":
            break
        (
            _sig,
            _vmb,
            _vnb,
            _flags,
            method,
            _mtime,
            _mdate,
            crc,
            csize,
            usize,
            nlen,
            elen,
            clen,
            _dstart,
            _iattr,
            _eattr,
            lhoff,
        ) = struct.unpack("<IHHHHHHIIIHHHHHII", blob[off : off + 46])

        name = blob[off + 46 : off + 46 + nlen].decode("utf-8", "replace")
        extra = blob[off + 46 + nlen : off + 46 + nlen + elen]

        # ZIP64 extended information overrides the 0xFFFFFFFF sentinels.
        eo = 0
        while eo + 4 <= len(extra):
            hid, hsz = struct.unpack("<HH", extra[eo : eo + 4])
            body = extra[eo + 4 : eo + 4 + hsz]
            if hid == 0x0001:
                bo = 0
                if usize == 0xFFFFFFFF and bo + 8 <= len(body):
                    usize = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
                if csize == 0xFFFFFFFF and bo + 8 <= len(body):
                    csize = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
                if lhoff == 0xFFFFFFFF and bo + 8 <= len(body):
                    lhoff = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
            eo += 4 + hsz

        members.append(Member(name, method, usize, csize, lhoff, crc))
        off += 46 + nlen + elen + clen
    return members


def read_members(url: str, verbose: bool = True) -> tuple[int, list[Member]]:
    """Fetch and parse the central directory. Downloads ~45 MB, not the archive.

    Returns (archive_size, members). This is the form the kernels use;
    build_index() wraps it for the on-disk index artifact.
    """
    total = remote_size(url)
    if verbose:
        print(f"archive size: {total:,} bytes", flush=True)

    tail = http_get(url, total - 65_536, total - 1)
    n_entries, cd_size, cd_off = _find_eocd(tail)
    if verbose:
        print(
            f"central directory: {n_entries:,} entries, "
            f"{cd_size:,} bytes at offset {cd_off:,}",
            flush=True,
        )

    blob = http_get(url, cd_off, cd_off + cd_size - 1)
    members = parse_central_directory(blob)
    if len(members) != n_entries:
        print(
            f"WARNING: parsed {len(members)} entries, EOCD claims {n_entries}",
            file=sys.stderr,
        )

    return total, members


def build_index(url: str, verbose: bool = True) -> dict:
    """Serialisable index for the on-disk artifact (scripts/build_zip_index.py)."""
    total, members = read_members(url, verbose=verbose)
    return {
        "archive": ARCHIVE_NAME,
        "archive_size": total,
        "archive_md5": ARCHIVE_MD5 if total == ARCHIVE_SIZE else None,
        "source_url": url,
        "entry_count": len(members),
        "members": [asdict(m) for m in members],
    }


def save_index(path: str, index: dict) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(index, fh)


def load_index(path: str) -> tuple[dict, list[Member]]:
    with open(path, encoding="utf-8") as fh:
        index = json.load(fh)
    return index, [Member(**m) for m in index["members"]]


# --------------------------------------------------------------------------
# Extraction
# --------------------------------------------------------------------------


def sniff_image_ext(data: bytes) -> str | None:
    """Return the real extension for an image payload, or None if unknown.

    The dataset's depth frames are named ``*.jpg`` but are actually PNG
    (magic 89 50 4E 47). Anything decoding by extension will mislabel them.
    """
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return ".png"
    if data[:2] == b"\xff\xd8":
        return ".jpg"
    return None


def _run_end(member: Member, archive_size: int) -> int:
    """Exclusive upper bound on the bytes a member can occupy."""
    return min(
        archive_size,
        member.offset
        + 30
        + len(member.name.encode())
        + _LOCAL_EXTRA_PAD
        + member.csize,
    )


def plan_runs(
    members: list[Member],
    archive_size: int,
    gap_merge: int = 1 << 20,
    max_run_bytes: int = 256 << 20,
) -> list[tuple[int, int, list[Member]]]:
    """Group members into contiguous byte runs to keep the request count sane.

    Fetching 130k tiny annotation files one request each is not viable; the
    annotation directories are physically contiguous at the end of the archive
    so they collapse into a handful of runs.
    """
    ordered = sorted((m for m in members if not m.is_dir), key=lambda m: m.offset)
    runs: list[tuple[int, int, list[Member]]] = []
    for m in ordered:
        m_end = _run_end(m, archive_size)
        if runs:
            start, end, group = runs[-1]
            if m.offset - end <= gap_merge and (m_end - start) <= max_run_bytes:
                group.append(m)
                runs[-1] = (start, max(end, m_end), group)
                continue
        runs.append((m.offset, m_end, [m]))
    return runs


def _member_data(buf: bytes, member: Member, base: int, url: str) -> tuple[bytes, int]:
    """Slice one member out of a run buffer and decompress it.

    Falls back to an exact range request for whatever the run buffer did not
    cover, so the run-end estimate never has to be conservative. Returns
    (data, extra_requests).
    """
    extra = 0
    pos = member.offset - base
    if pos < 0 or pos + 30 > len(buf):
        header = http_get(url, member.offset, member.offset + 29)
        extra += 1
    else:
        header = buf[pos : pos + 30]

    sig, _ver, _flg, _meth, _t, _d, _crc, _c, _u, nlen, elen = struct.unpack(
        "<IHHHHHIIIHH", header
    )
    if sig != 0x04034B50:
        raise ValueError(f"bad local header signature for {member.name}")

    data_start = member.offset + 30 + nlen + elen
    lo = data_start - base
    if lo >= 0 and lo + member.csize <= len(buf):
        raw = buf[lo : lo + member.csize]
    else:
        raw = http_get(url, data_start, data_start + member.csize - 1)
        extra += 1
    if len(raw) != member.csize:
        raise ValueError(f"short read for {member.name}")

    data = zlib.decompress(raw, -15) if member.method == 8 else raw
    if member.crc and zlib.crc32(data) & 0xFFFFFFFF != member.crc:
        raise ValueError(f"CRC mismatch for {member.name}")
    return data, extra


def extract_members(
    url: str,
    members: list[Member],
    out_dir: str,
    archive_size: int = ARCHIVE_SIZE,
    strip_prefix: str = ROOT_PREFIX,
    gap_merge: int = 1 << 20,
    max_run_bytes: int = 256 << 20,
    fix_image_extensions: bool = True,
    verbose: bool = True,
) -> dict:
    """Download and inflate the given members into out_dir.

    Returns a summary dict. Members are written at their archive-relative
    path with ``strip_prefix`` removed. When ``fix_image_extensions`` is set,
    a file whose payload disagrees with its extension is written with the
    correct one (this is what handles the depth-frames-are-PNG problem).
    """
    runs = plan_runs(members, archive_size, gap_merge, max_run_bytes)
    planned = sum(end - start for start, end, _ in runs)
    if verbose:
        print(
            f"extracting {len(members):,} members in {len(runs):,} range request(s); "
            f"~{planned / 1e9:.3f} GB to transfer",
            flush=True,
        )

    written = 0
    bytes_out = 0
    extra_requests = 0
    renamed: list[tuple[str, str]] = []
    t0 = time.time()

    for idx, (start, end, group) in enumerate(runs, 1):
        buf = http_get(url, start, end - 1)
        for m in group:
            data, extra = _member_data(buf, m, start, url)
            extra_requests += extra
            rel = (
                m.name[len(strip_prefix) :]
                if m.name.startswith(strip_prefix)
                else m.name
            )
            if fix_image_extensions:
                stem, ext = os.path.splitext(rel)
                real = sniff_image_ext(data[:8])
                if (
                    real
                    and ext.lower() in {".jpg", ".jpeg", ".png"}
                    and real != ext.lower()
                ):
                    renamed.append((rel, stem + real))
                    rel = stem + real
            dst = os.path.join(out_dir, rel.replace("/", os.sep))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            with open(dst, "wb") as fh:
                fh.write(data)
            written += 1
            bytes_out += len(data)
        if verbose and (idx % 25 == 0 or idx == len(runs)):
            rate = planned / max(time.time() - t0, 1e-6) / 1e6
            print(
                f"  run {idx}/{len(runs)}  files={written:,}  "
                f"out={bytes_out / 1e9:.3f} GB  ~{rate:.1f} MB/s",
                flush=True,
            )

    if renamed and verbose:
        print(
            f"  corrected {len(renamed)} file extension(s) after magic-byte sniff "
            f"(e.g. {renamed[0][0]} -> {renamed[0][1]})",
            flush=True,
        )

    return {
        "members": written,
        "bytes_written": bytes_out,
        "bytes_transferred_planned": planned,
        "runs": len(runs),
        "extra_requests": extra_requests,
        "renamed": renamed[:50],
        "renamed_total": len(renamed),
        "seconds": round(time.time() - t0, 1),
    }

# ---- src/sanas/selection.py ---------------------------------------
import bisect
import os
from dataclasses import dataclass, field

ROOT_PREFIX = "beintelli_v1/"

ROOT_METADATA = {
    ROOT_PREFIX + "person_states.json",
    ROOT_PREFIX + "modalities.json",
    ROOT_PREFIX + "frame_ids.json",
    ROOT_PREFIX + "target_transforms.json",
}

COLOR_CAMERAS = [
    "front_left_color",
    "front_right_color",
    "center_left_color",
    "back_right_color",
]

NS_PER_MS = 1_000_000

# What the already-executed single-camera extraction produced. Any change to
# selection logic that moves these numbers is drift and must be deliberate.
SINGLE_CAMERA_EXPECTATION = {
    "images": 1289,
    "depth": 1204,
    "labels": 32911,
    "total_members": 35404,
}


@dataclass
class SubsetSpec:
    """Which archive members a run wants."""

    color_cameras: list = field(default_factory=lambda: ["front_left_color"])
    # Depth streams to pull. None -> the depth twin of each colour camera.
    depth_cameras: list | None = None
    # Colour camera whose frame times define the sampling grid. All depth
    # streams are matched to these instants so the cameras stay in sync.
    timebase_camera: str | None = None
    stride: int = 10
    max_images: int = 0
    include_depth: bool = True
    include_masks: bool = False
    include_poses: bool = False
    depth_tolerance_ms: int = 100

    def resolved_depth_cameras(self) -> list:
        if self.depth_cameras is not None:
            return list(self.depth_cameras)
        if not self.include_depth:
            return []
        return [c.replace("_color", "_depth") for c in self.color_cameras]

    def resolved_timebase(self) -> str:
        return self.timebase_camera or self.color_cameras[0]


def timestamp_of(name: str) -> int | None:
    """19-digit nanosecond stamp from a member name, or None."""
    stem = os.path.splitext(os.path.basename(name))[0].split("_")[0]
    return int(stem) if stem.isdigit() and len(stem) == 19 else None


def nearest(ts: int, sorted_ts: list, tolerance_ns: int) -> int | None:
    if not sorted_ts:
        return None
    i = bisect.bisect_left(sorted_ts, ts)
    best = None
    for j in (i - 1, i):
        if 0 <= j < len(sorted_ts):
            d = abs(sorted_ts[j] - ts)
            if d <= tolerance_ns and (best is None or d < abs(best - ts)):
                best = sorted_ts[j]
    return best


def select_members(members, spec: SubsetSpec):
    """Return (selected_members, breakdown_dict) for a SubsetSpec."""
    timebase = spec.resolved_timebase()
    depth_cams = spec.resolved_depth_cameras()

    # ---- colour frames -------------------------------------------------
    images = []
    per_camera_images = {}
    for cam in spec.color_cameras:
        cam_imgs = sorted(
            (
                m
                for m in members
                if m.name.startswith(f"{ROOT_PREFIX}cameras/color/{cam}/images/")
                and m.name.endswith(".jpg")
            ),
            key=lambda m: m.name,
        )
        picked = cam_imgs[:: spec.stride]
        if spec.max_images:
            picked = picked[: spec.max_images]
        per_camera_images[cam] = picked
        images.extend(picked)

    timebase_ts = [timestamp_of(m.name) for m in per_camera_images.get(timebase, [])]
    timebase_ts = [t for t in timebase_ts if t is not None]

    # ---- annotations ---------------------------------------------------
    seg_prefixes = tuple(f"{ROOT_PREFIX}segmentations/{c}/" for c in spec.color_cameras)
    labels = []
    for m in members:
        n = m.name
        if m.is_dir:
            continue
        if n.startswith(seg_prefixes):
            if n.endswith(".json") or (spec.include_masks and n.endswith(".png")):
                labels.append(m)
        elif n.startswith(f"{ROOT_PREFIX}bboxes_3d/") or n.startswith(
            f"{ROOT_PREFIX}states/"
        ):
            labels.append(m)
        elif spec.include_poses and n.startswith(f"{ROOT_PREFIX}poses/"):
            labels.append(m)
        elif n in ROOT_METADATA:
            labels.append(m)
        elif n.startswith(f"{ROOT_PREFIX}cameras/") and n.endswith("camera_info.yaml"):
            labels.append(m)

    # ---- depth frames, matched to the timebase -------------------------
    depth = []
    per_camera_depth = {}
    tol = spec.depth_tolerance_ms * NS_PER_MS
    for dcam in depth_cams:
        cand = {}
        for m in members:
            if m.is_dir:
                continue
            if not m.name.startswith(f"{ROOT_PREFIX}cameras/depth/{dcam}/images/"):
                continue
            t = timestamp_of(m.name)
            if t is not None:
                cand[t] = m
        keys = sorted(cand)
        seen, chosen = set(), []
        for t in timebase_ts:
            hit = nearest(t, keys, tol)
            if hit is not None and hit not in seen:
                seen.add(hit)
                chosen.append(cand[hit])
        per_camera_depth[dcam] = chosen
        depth.extend(chosen)

    selected = images + labels + depth
    breakdown = {
        "timebase_camera": timebase,
        "stride": spec.stride,
        "images": len(images),
        "image_bytes": sum(m.csize for m in images),
        "labels": len(labels),
        "label_bytes": sum(m.csize for m in labels),
        "depth": len(depth),
        "depth_bytes": sum(m.csize for m in depth),
        "total_members": len(selected),
        "total_compressed_bytes": sum(m.csize for m in selected),
        "per_camera_images": {c: len(v) for c, v in per_camera_images.items()},
        "per_camera_depth": {c: len(v) for c, v in per_camera_depth.items()},
        "per_camera_depth_bytes": {
            c: sum(m.csize for m in v) for c, v in per_camera_depth.items()
        },
    }
    return selected, breakdown


def check_single_camera_regression(breakdown: dict, keys=None) -> list:
    """Compare a single-camera breakdown against what already ran.

    `keys` limits the comparison, because a run that deliberately skips depth
    cannot be expected to match the depth-inclusive frame counts. Returns a
    list of human-readable mismatches; empty means no drift.
    """
    problems = []
    for key, expected in SINGLE_CAMERA_EXPECTATION.items():
        if keys is not None and key not in keys:
            continue
        actual = breakdown.get(key)
        if actual != expected:
            problems.append(f"{key}: expected {expected:,}, got {actual:,}")
    return problems

# ---- src/sanas/labels.py ------------------------------------------
import bisect
import json
import os

NS_PER_MS = 1_000_000


def counts_from_segmentation(
    payload: bytes | str, score_threshold: float = 0.0
) -> tuple[int, float | None]:
    """Return (person_count, min_score) for one segmentation JSON."""
    entries = json.loads(payload)
    if not isinstance(entries, list):
        raise ValueError("segmentation JSON is not a list")
    kept = [e for e in entries if float(e.get("score", 1.0)) >= score_threshold]
    min_score = min((float(e.get("score", 1.0)) for e in kept), default=None)
    return len(kept), min_score


def counts_from_bboxes(payload: bytes | str, label: str = "human") -> int:
    """Return the number of oriented 3D boxes with the given label."""
    entries = json.loads(payload)
    if not isinstance(entries, list):
        raise ValueError("bboxes_3d JSON is not a list")
    return sum(1 for e in entries if e.get("bbox_label") == label)


def _ts_from_filename(path: str) -> int | None:
    stem = os.path.splitext(os.path.basename(path))[0]
    stem = stem.split("_")[0]
    return int(stem) if stem.isdigit() and len(stem) == 19 else None


def load_view_counts(
    subset_dir: str, camera: str, score_threshold: float = 0.0
) -> dict[int, tuple[int, float | None]]:
    """Map camera timestamp -> (count_view, min_score) for one camera."""
    seg_dir = os.path.join(subset_dir, "segmentations", camera)
    out: dict[int, tuple[int, float | None]] = {}
    if not os.path.isdir(seg_dir):
        return out
    for name in os.listdir(seg_dir):
        if not name.endswith(".json"):
            continue
        ts = _ts_from_filename(name)
        if ts is None:
            continue
        with open(os.path.join(seg_dir, name), "rb") as fh:
            out[ts] = counts_from_segmentation(fh.read(), score_threshold)
    return out


def load_cabin_counts(subset_dir: str) -> dict[int, int]:
    """Map lidar timestamp -> total occupants from bboxes_3d."""
    box_dir = os.path.join(subset_dir, "bboxes_3d")
    out: dict[int, int] = {}
    if not os.path.isdir(box_dir):
        return out
    for name in os.listdir(box_dir):
        if not name.endswith(".json"):
            continue
        ts = _ts_from_filename(name)
        if ts is None:
            continue
        with open(os.path.join(box_dir, name), "rb") as fh:
            out[ts] = counts_from_bboxes(fh.read())
    return out


def match_nearest(ts: int, sorted_ts: list[int], tolerance_ns: int) -> int | None:
    """Nearest timestamp in sorted_ts within tolerance, else None."""
    if not sorted_ts:
        return None
    i = bisect.bisect_left(sorted_ts, ts)
    best = None
    for j in (i - 1, i):
        if 0 <= j < len(sorted_ts):
            d = abs(sorted_ts[j] - ts)
            if d <= tolerance_ns and (best is None or d < abs(best - ts)):
                best = sorted_ts[j]
    return best


def assign_sequences(sorted_ts: list[int], gap_ns: int = 5 * 10**9) -> dict[int, int]:
    """Split a timestamp list into sub-sequences at recording gaps.

    Frames are ~0.067 s apart, so a random train/val split leaks near-duplicate
    neighbours across the boundary. The recording has 10 gaps > 5 s in
    front_left_color, giving 11 sub-sequences to split on instead.
    """
    seq: dict[int, int] = {}
    current = 0
    for i, ts in enumerate(sorted_ts):
        if i and ts - sorted_ts[i - 1] > gap_ns:
            current += 1
        seq[ts] = current
    return seq


def build_label_table(
    subset_dir: str,
    camera: str,
    score_threshold: float = 0.0,
    cabin_tolerance_ns: int = 100 * NS_PER_MS,
    sequence_gap_ns: int = 5 * 10**9,
) -> list[dict]:
    """Join extracted images with their counts into one row per frame."""
    img_dir = os.path.join(subset_dir, "cameras", "color", camera, "images")
    if not os.path.isdir(img_dir):
        raise FileNotFoundError(f"no extracted images at {img_dir}")

    images: dict[int, str] = {}
    for name in sorted(os.listdir(img_dir)):
        ts = _ts_from_filename(name)
        if ts is not None:
            images[ts] = f"cameras/color/{camera}/images/{name}"

    view = load_view_counts(subset_dir, camera, score_threshold)
    cabin = load_cabin_counts(subset_dir)
    cabin_ts = sorted(cabin)

    ordered = sorted(images)
    seq = assign_sequences(ordered, sequence_gap_ns)

    rows: list[dict] = []
    for ts in ordered:
        v = view.get(ts)
        c_ts = match_nearest(ts, cabin_ts, cabin_tolerance_ns)
        rows.append(
            {
                "timestamp": ts,
                "camera": camera,
                "image": images[ts],
                "sequence": seq[ts],
                "count_view": None if v is None else v[0],
                "min_score": None if v is None else v[1],
                "count_cabin": None if c_ts is None else cabin[c_ts],
                "cabin_dt_ns": None if c_ts is None else c_ts - ts,
            }
        )
    return rows


def count_distribution(rows: list[dict], column: str) -> dict[str, int]:
    dist: dict[str, int] = {}
    for r in rows:
        key = "missing" if r.get(column) is None else str(r[column])
        dist[key] = dist.get(key, 0) + 1
    return dict(sorted(dist.items(), key=lambda kv: (kv[0] == "missing", kv[0])))


def write_labels(path: str, rows: list[dict]) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")


def read_labels(path: str) -> list[dict]:
    with open(path, encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]

# ---- src/sanas/fetch.py -------------------------------------------
import json
import os
import sys



def default_work_dir() -> str:
    return (
        "/kaggle/working/subset"
        if os.path.isdir("/kaggle/working")
        else os.path.join("data", "subset")
    )


def fetch_subset(
    work: str | None = None,
    mirror: str = "hf",
    camera: str = "front_left_color",
    stride: int = 10,
    max_images: int = 0,
    depth_cameras: list | None = None,
    include_depth: bool = True,
    score_threshold: float = 0.0,
    dry_run: bool = False,
    no_fetch: bool = False,
    check_regression: bool = True,
    verbose: bool = True,
) -> tuple[str, dict]:
    """Ensure a usable subset exists at `work`. Returns (work_dir, info)."""
    work = work or default_work_dir()
    labels_path = os.path.join(work, "labels.jsonl")

    if no_fetch:
        if not os.path.exists(labels_path):
            raise SystemExit(f"--no-fetch given but {labels_path} is missing")
        if verbose:
            print(f"--no-fetch: reusing existing subset at {work}")
        return work, {"fetched": False}

    spec = SubsetSpec(
        color_cameras=[camera],
        depth_cameras=depth_cameras,
        timebase_camera=camera,
        stride=stride,
        max_images=max_images,
        include_depth=include_depth,
    )

    url = MIRRORS[mirror]
    if verbose:
        print(f"mirror: {mirror}")
    archive_size, members = read_members(url, verbose=verbose)
    if archive_size != ARCHIVE_SIZE:
        print(
            f"WARNING: archive is {archive_size:,} bytes, expected {ARCHIVE_SIZE:,}",
            file=sys.stderr,
        )

    selected, breakdown = select_members(members, spec)
    if verbose:
        print("\nselection (shared definition, src/sanas/selection.py):")
        for k in (
            "images",
            "labels",
            "depth",
            "total_members",
            "total_compressed_bytes",
        ):
            print(f"  {k:<26} {breakdown[k]:,}")
        print(f"  {'GB selected':<26} {breakdown['total_compressed_bytes'] / 1e9:.3f}")
        print(f"  per-camera depth frames    {breakdown['per_camera_depth']}")

    single_default = (
        check_regression
        and stride == 10
        and max_images == 0
        and camera == "front_left_color"
        and len(spec.resolved_depth_cameras()) <= 1
    )
    if single_default and verbose:
        keys = (
            ("images", "labels", "depth", "total_members")
            if include_depth
            else ("images", "labels")
        )
        problems = check_single_camera_regression(breakdown, keys=keys)
        print(
            "  regression vs executed run: "
            + ("CLEAN" if not problems else "DRIFT -> " + "; ".join(problems))
        )

    if dry_run:
        runs = plan_runs(selected, archive_size)
        planned = sum(e - s for s, e, _ in runs)
        print(
            f"\n--dry-run: would issue {len(runs):,} range request(s), "
            f"~{planned / 1e9:.3f} GB. Nothing downloaded."
        )
        raise SystemExit(0)

    os.makedirs(work, exist_ok=True)
    stats = extract_members(
        url, selected, work, archive_size=archive_size, verbose=verbose
    )
    if verbose:
        print(
            f"\nextracted {stats['members']:,} files, "
            f"{stats['bytes_written'] / 1e9:.3f} GB in {stats['seconds']}s "
            f"({stats['renamed_total']:,} extensions corrected by magic-byte sniff)"
        )

    rows = build_label_table(work, camera, score_threshold=score_threshold)
    with open(labels_path, "w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")
    if verbose:
        print(f"labels: {len(rows):,} rows -> {labels_path}")
        print(f"count_view  {count_distribution(rows, 'count_view')}")
        print(f"count_cabin {count_distribution(rows, 'count_cabin')}")

    return work, {"fetched": True, "selection": breakdown, "transfer": stats}

# ---- src/sanas/depth_occupancy.py ---------------------------------
import json
import math
import os
import re
from dataclasses import dataclass

import numpy as np

DEPTH_SCALE_M = 0.001  # uint16 millimetres -> metres
UINT16_SATURATION = 65535


# --------------------------------------------------------------------------
# Calibration
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Intrinsics:
    width: int
    height: int
    fx: float
    fy: float
    cx: float
    cy: float
    distortion: tuple[float, ...] = ()

    @property
    def has_distortion(self) -> bool:
        return any(abs(d) > 1e-9 for d in self.distortion)


def _yaml_floats(text: str, block: str) -> list[float]:
    m = re.search(rf"{block}:.*?data:\s*((?:\s*-\s*[-\d.eE+]+\s*\n)+)", text, re.S)
    if not m:
        return []
    return [float(x) for x in re.findall(r"-?\d+\.?\d*(?:[eE][-+]?\d+)?", m.group(1))]


def load_intrinsics(path: str) -> Intrinsics:
    """Parse a ROS camera_info.yaml.

    Deliberately a small regex parser rather than a PyYAML dependency: the
    file shape is fixed and this keeps the CPU kernel free of extra installs.
    """
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    k = _yaml_floats(text, "camera_matrix")
    if len(k) < 9:
        raise ValueError(f"no camera_matrix in {path}")
    w = re.search(r"image_width:\s*(\d+)", text)
    h = re.search(r"image_height:\s*(\d+)", text)
    return Intrinsics(
        width=int(w.group(1)) if w else 0,
        height=int(h.group(1)) if h else 0,
        fx=k[0],
        fy=k[4],
        cx=k[2],
        cy=k[5],
        distortion=tuple(_yaml_floats(text, "distortion_coefficients")),
    )


def rpy_to_matrix(roll: float, pitch: float, yaw: float) -> np.ndarray:
    """URDF fixed-axis roll-pitch-yaw -> 3x3 rotation (Rz @ Ry @ Rx)."""
    cr, sr = math.cos(roll), math.sin(roll)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cy, sy = math.cos(yaw), math.sin(yaw)
    rx = np.array([[1, 0, 0], [0, cr, -sr], [0, sr, cr]], dtype=np.float64)
    ry = np.array([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]], dtype=np.float64)
    rz = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]], dtype=np.float64)
    return rz @ ry @ rx


def _joint_matrix(entry: dict) -> np.ndarray:
    xyz = [float(v) for v in str(entry["xyz"]).split()]
    rpy = [float(v) for v in str(entry["rpy"]).split()]
    t = np.eye(4)
    t[:3, :3] = rpy_to_matrix(*rpy)
    t[:3, 3] = xyz
    return t


def load_extrinsics(
    subset_dir: str, camera: str, root_frame: str = "base_link"
) -> np.ndarray:
    """4x4 transform taking points from a camera's optical frame to root_frame.

    Uses only archive data: frame_ids.json (camera -> optical frame name) and
    target_transforms.json (URDF joint chain, child expressed in parent).
    Raises if the chain cannot be resolved, so a caller can fall back to
    per-camera frustum occupancy instead of silently using a wrong frame.
    """
    with open(os.path.join(subset_dir, "frame_ids.json"), encoding="utf-8") as fh:
        frame_ids = json.load(fh)
    with open(
        os.path.join(subset_dir, "target_transforms.json"), encoding="utf-8"
    ) as fh:
        transforms = json.load(fh)

    frame = frame_ids.get(camera)
    if frame is None:
        raise KeyError(f"camera {camera!r} not in frame_ids.json")
    chain = transforms.get(frame)
    if not chain:
        raise KeyError(f"frame {frame!r} has no entry in target_transforms.json")

    # Entries are ordered child-first: [aruco->cam, base->aruco]. Compose from
    # the root down, so multiply in reverse order.
    t = np.eye(4)
    for entry in reversed(chain):
        t = t @ _joint_matrix(entry)

    parents = [e.get("parent") for e in chain]
    if root_frame not in parents:
        raise ValueError(
            f"chain for {frame!r} does not reach {root_frame!r}; parents={parents}"
        )
    return t


# --------------------------------------------------------------------------
# Depth -> points
# --------------------------------------------------------------------------


def load_depth_metres(path: str) -> np.ndarray:
    """Read a depth frame as float32 metres. Decodes by content, not extension.

    The archive names depth frames ``*.jpg`` while the payload is PNG; PIL
    sniffs the magic bytes so this works either way, but never assume the
    extension elsewhere.
    """
    from PIL import Image

    arr = np.array(Image.open(path))
    if arr.dtype != np.uint16:
        raise ValueError(f"expected uint16 depth, got {arr.dtype} in {path}")
    out = arr.astype(np.float32) * DEPTH_SCALE_M
    out[arr == UINT16_SATURATION] = 0.0  # saturated = no measurement
    return out


def depth_range_stats(depth_m: np.ndarray, min_range: float, max_range: float) -> dict:
    """Per-frame accounting of how much of the frame is actually usable."""
    total = depth_m.size
    zero = int((depth_m <= 0).sum())
    inside = int(((depth_m >= min_range) & (depth_m <= max_range)).sum())
    beyond = int((depth_m > max_range).sum())
    near = int(((depth_m > 0) & (depth_m < min_range)).sum())
    return {
        "pixels": total,
        "frac_zero": zero / total,
        "frac_in_range": inside / total,
        "frac_beyond_max": beyond / total,
        "frac_below_min": near / total,
    }


def deproject(
    depth_m: np.ndarray,
    intr: Intrinsics,
    min_range: float = 0.3,
    max_range: float = 3.0,
    pixel_stride: int = 4,
) -> np.ndarray:
    """Depth image -> (N,3) points in the camera optical frame (x right, y down, z forward)."""
    if intr.has_distortion:
        raise NotImplementedError(
            "intrinsics carry non-zero distortion; this deprojection assumes "
            "rectified depth (all four cameras in this archive report zeros)"
        )
    d = depth_m[::pixel_stride, ::pixel_stride]
    ys, xs = np.nonzero((d >= min_range) & (d <= max_range))
    if xs.size == 0:
        return np.empty((0, 3), dtype=np.float32)
    z = d[ys, xs]
    u = xs.astype(np.float32) * pixel_stride
    v = ys.astype(np.float32) * pixel_stride
    x = (u - intr.cx) * z / intr.fx
    y = (v - intr.cy) * z / intr.fy
    return np.stack([x, y, z], axis=1).astype(np.float32)


def transform_points(points: np.ndarray, t: np.ndarray) -> np.ndarray:
    if points.size == 0:
        return points
    return (points @ t[:3, :3].T + t[:3, 3]).astype(np.float32)


# --------------------------------------------------------------------------
# BEV occupancy
# --------------------------------------------------------------------------


@dataclass
class GridConfig:
    """BEV grid in the cabin frame. Defaults are metres."""

    cell_size: float = 0.10
    x_min: float = -6.0
    x_max: float = 6.0
    y_min: float = -6.0
    y_max: float = 6.0
    z_min: float = 0.6  # above seat height: ignore floor and seat pans
    z_max: float = 2.0  # below ceiling
    min_points_per_cell: int = 3

    @property
    def shape(self) -> tuple[int, int]:
        return (
            int(round((self.x_max - self.x_min) / self.cell_size)),
            int(round((self.y_max - self.y_min) / self.cell_size)),
        )


def bev_grid(points: np.ndarray, cfg: GridConfig) -> np.ndarray:
    """Boolean occupancy grid over the cabin floor plan."""
    nx, ny = cfg.shape
    grid = np.zeros((nx, ny), dtype=np.int32)
    if points.size == 0:
        return grid > 0
    m = (
        (points[:, 2] >= cfg.z_min)
        & (points[:, 2] <= cfg.z_max)
        & (points[:, 0] >= cfg.x_min)
        & (points[:, 0] < cfg.x_max)
        & (points[:, 1] >= cfg.y_min)
        & (points[:, 1] < cfg.y_max)
    )
    p = points[m]
    if p.size == 0:
        return grid > 0
    ix = ((p[:, 0] - cfg.x_min) / cfg.cell_size).astype(np.int32)
    iy = ((p[:, 1] - cfg.y_min) / cfg.cell_size).astype(np.int32)
    np.add.at(grid, (ix, iy), 1)
    return grid >= cfg.min_points_per_cell


def build_background(grids: list[np.ndarray], quantile: float = 0.5) -> np.ndarray:
    """Empty-cabin reference: cells occupied in at least `quantile` of frames.

    Built from frames whose ground-truth occupant count is zero, so fixed cabin
    structure is subtracted instead of being scored as people.
    """
    if not grids:
        raise ValueError("no zero-occupancy frames available to build a background")
    stack = np.stack(grids, axis=0)
    return stack.mean(axis=0) >= quantile


def occupancy_score(grid: np.ndarray, background: np.ndarray) -> tuple[float, int]:
    """Fraction of non-background cells that are occupied. Returns (score, cells)."""
    foreground = grid & ~background
    denom = int((~background).sum())
    cells = int(foreground.sum())
    return (cells / denom if denom else 0.0), cells


# --------------------------------------------------------------------------
# Metrics (numpy only, no scipy)
# --------------------------------------------------------------------------


def pearson(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)
    if a.size < 2 or a.std() == 0 or b.std() == 0:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])


def _rankdata(x: np.ndarray) -> np.ndarray:
    """Average ranks, ties shared."""
    x = np.asarray(x, dtype=np.float64)
    order = np.argsort(x, kind="mergesort")
    ranks = np.empty(x.size, dtype=np.float64)
    ranks[order] = np.arange(1, x.size + 1, dtype=np.float64)
    # average tied groups
    sx = x[order]
    i = 0
    while i < sx.size:
        j = i
        while j + 1 < sx.size and sx[j + 1] == sx[i]:
            j += 1
        if j > i:
            ranks[order[i : j + 1]] = ranks[order[i : j + 1]].mean()
        i = j + 1
    return ranks


def spearman(a: np.ndarray, b: np.ndarray) -> float:
    return pearson(_rankdata(a), _rankdata(b))


def bootstrap_ci(
    x: np.ndarray,
    y: np.ndarray,
    stat,
    n_boot: int = 1000,
    seed: int = 0,
    alpha: float = 0.05,
) -> tuple[float, float]:
    """Percentile bootstrap CI for a correlation statistic.

    Reported because a point estimate looks authoritative and this subset
    cannot support one: the top occupancy level has very few frames, so the
    interval is the honest summary.
    """
    x = np.asarray(x)
    y = np.asarray(y)
    if x.size < 3:
        return (float("nan"), float("nan"))
    rng = np.random.default_rng(seed)
    vals = []
    for _ in range(n_boot):
        idx = rng.integers(0, x.size, x.size)
        v = stat(x[idx], y[idx])
        if not math.isnan(v):
            vals.append(v)
    if not vals:
        return (float("nan"), float("nan"))
    return (
        float(np.percentile(vals, 100 * alpha / 2)),
        float(np.percentile(vals, 100 * (1 - alpha / 2))),
    )


def fragility_warnings(counts: np.ndarray, min_per_level: int = 100) -> list[str]:
    """Reasons not to trust a correlation computed on this data."""
    counts = np.asarray(counts)
    out = []
    levels, freq = np.unique(counts, return_counts=True)
    thin = [(int(a), int(b)) for a, b in zip(levels, freq) if b < min_per_level]
    if thin:
        out.append(
            "sparse levels (fewer than "
            f"{min_per_level} frames): "
            + ", ".join(f"count {a}: n={b}" for a, b in thin)
        )
    if levels.max() < 4:
        out.append(
            f"highest occupancy observed is {int(levels.max())}; the dataset "
            "never exceeds 4 and this subset tops out lower still, so nothing "
            "here speaks to a full cabin"
        )
    if len(levels) < 3:
        out.append(f"only {len(levels)} distinct levels present")
    return out


# --------------------------------------------------------------------------
# Multi-camera rig
# --------------------------------------------------------------------------


def observed_cells(points: np.ndarray, cfg: "GridConfig") -> np.ndarray:
    """Cells where a camera returned ANY usable range measurement.

    Uses a wide vertical band and a single-point threshold: this is about the
    sensor's footprint on the floor plan, not about detecting people.
    """
    import dataclasses

    wide = dataclasses.replace(cfg, z_min=-0.5, z_max=2.5, min_points_per_cell=1)
    return bev_grid(points, wide)


def merge_grids(grids: list[np.ndarray]) -> np.ndarray:
    """Union of per-camera boolean grids."""
    if not grids:
        raise ValueError("no grids to merge")
    out = np.zeros_like(grids[0], dtype=bool)
    for g in grids:
        out |= g
    return out


def person_region_cells(
    bbox_dir: str, cfg: "GridConfig", dilate_m: float = 0.30, label: str = "human"
) -> np.ndarray:
    """BEV cells where annotated occupants actually appear, over the whole recording.

    This is the denominator for floor coverage. There is no cabin floor polygon
    in the archive, so rather than inventing one, the region people are known
    to occupy is derived from every 3D box in bboxes_3d and dilated by roughly
    a person's radius. Cells outside this are floor we do not need to see.
    """
    nx, ny = cfg.shape
    grid = np.zeros((nx, ny), dtype=bool)
    if not os.path.isdir(bbox_dir):
        return grid
    xs, ys = [], []
    for name in os.listdir(bbox_dir):
        if not name.endswith(".json"):
            continue
        with open(os.path.join(bbox_dir, name), "rb") as fh:
            try:
                entries = json.load(fh)
            except json.JSONDecodeError:
                continue
        for e in entries:
            if e.get("bbox_label") != label:
                continue
            c = e.get("bbox_center")
            if c and len(c) >= 2:
                xs.append(float(c[0]))
                ys.append(float(c[1]))
    if not xs:
        return grid
    r = max(0, int(round(dilate_m / cfg.cell_size)))
    for x, y in zip(xs, ys):
        ix = int((x - cfg.x_min) / cfg.cell_size)
        iy = int((y - cfg.y_min) / cfg.cell_size)
        lo_x, hi_x = max(0, ix - r), min(nx, ix + r + 1)
        lo_y, hi_y = max(0, iy - r), min(ny, iy + r + 1)
        if lo_x < hi_x and lo_y < hi_y:
            grid[lo_x:hi_x, lo_y:hi_y] = True
    return grid


def coverage_report(per_camera_observed: dict, region: np.ndarray) -> dict:
    """How much of the occupied-region floor the rig can actually see."""
    union = merge_grids(list(per_camera_observed.values()))
    region_cells = int(region.sum())
    covered = int((union & region).sum())
    per_camera = {
        cam: {
            "observed_cells": int(g.sum()),
            "region_cells_covered": int((g & region).sum()),
            "region_fraction": (float((g & region).sum()) / region_cells)
            if region_cells
            else 0.0,
        }
        for cam, g in per_camera_observed.items()
    }
    return {
        "region_cells": region_cells,
        "covered_cells": covered,
        "uncovered_cells": region_cells - covered,
        "coverage_fraction": (covered / region_cells) if region_cells else 0.0,
        "per_camera": per_camera,
    }

# ---- src/sanas/depth_kernel.py ------------------------------------
import argparse
import json
import os
import sys
import time

import numpy as np


DIAGNOSTIC_INPUT_DIR = "/kaggle/input/notebooks/diypyzsdiyas/sanas-extract-subset"


def on_kaggle() -> bool:
    return os.path.isdir("/kaggle/working")


def report_mounted_kernel_source(path: str = DIAGNOSTIC_INPUT_DIR) -> dict:
    """Print what `kernel_sources` actually mounts. Names and sizes only.

    Cheap diagnostic: if one of these turns out to be a usable artifact the
    design could be simplified later, so it is worth one listing.
    """
    print("\n" + "-" * 72)
    print(f"DIAGNOSTIC: contents of {path}")
    print("-" * 72)
    if not os.path.isdir(path):
        print("  not mounted in this run")
        return {"mounted": False, "files": []}
    files = []
    for name in sorted(os.listdir(path)):
        full = os.path.join(path, name)
        kind = "dir" if os.path.isdir(full) else "file"
        size = os.path.getsize(full) if os.path.isfile(full) else 0
        files.append({"name": name, "kind": kind, "bytes": size})
        print(f"  {kind:<5} {size:>12,}  {name}")
    if not files:
        print("  (empty)")
    return {"mounted": True, "files": files}


def ensure_subset(args) -> tuple[str, dict]:
    """Fetch the subset by byte range. Delegates to the shared fetcher so the
    RGB and depth branches cannot select different frames."""
    depth_cams = (
        [c.replace("_color", "_depth") for c in COLOR_CAMERAS]
        if args.mode == "multi"
        else [args.camera.replace("_color", "_depth")]
    )
    return fetch_subset(
        work=args.data,
        mirror=args.mirror,
        camera=args.camera,
        stride=args.stride,
        max_images=args.max_images,
        depth_cameras=depth_cams,
        include_depth=True,
        score_threshold=args.score_threshold,
        dry_run=args.dry_run,
        no_fetch=args.no_fetch,
        check_regression=(args.mode == "single"),
    )


def build_rig(work: str, depth_cams: list) -> dict:
    """Per-camera intrinsics and camera->base_link transform."""
    rig = {}
    for cam in depth_cams:
        intr = load_intrinsics(
            os.path.join(work, "cameras", "depth", cam, "camera_info.yaml")
        )
        try:
            T = load_extrinsics(work, cam)
            ok = True
        except (KeyError, ValueError, FileNotFoundError) as exc:
            print(f"  WARNING: no cabin transform for {cam} ({exc}); using identity")
            T = np.eye(4)
            ok = False
        rig[cam] = {"intrinsics": intr, "T": T, "frame_resolved": ok}
        print(
            f"  {cam:<20} {intr.width}x{intr.height} fx={intr.fx:.1f} "
            f"origin_in_base={np.round(T[:3, 3], 2)}"
        )
    return rig


def index_depth_dir(work: str, cam: str) -> tuple[list, dict]:
    d = os.path.join(work, "cameras", "depth", cam, "images")
    idx = {}
    if os.path.isdir(d):
        for name in os.listdir(d):
            t = timestamp_of(name)
            if t is not None:
                idx[t] = os.path.join(d, name)
    return sorted(idx), idx


def score_frames(rows, work, rig, cfg, args):
    """Per-camera occupancy grids and observation footprints for every frame."""
    depth_index = {cam: index_depth_dir(work, cam) for cam in rig}
    tol = args.depth_tolerance_ms * 1_000_000

    grids = {cam: {} for cam in rig}
    observed = {cam: {} for cam in rig}
    range_acc = {cam: [] for cam in rig}
    matched = {cam: 0 for cam in rig}
    kept = []

    for r in rows:
        ts = int(r["timestamp"])
        per_cam_ok = False
        for cam, spec in rig.items():
            keys, idx = depth_index[cam]
            hit = nearest(ts, keys, tol)
            if hit is None:
                continue
            d = load_depth_metres(idx[hit])
            range_acc[cam].append(depth_range_stats(d, args.min_range, args.max_range))
            pts = transform_points(
                deproject(
                    d,
                    spec["intrinsics"],
                    args.min_range,
                    args.max_range,
                    args.pixel_stride,
                ),
                spec["T"],
            )
            grids[cam][ts] = bev_grid(pts, cfg)
            observed[cam][ts] = observed_cells(pts, cfg)
            matched[cam] += 1
            per_cam_ok = True
        if per_cam_ok:
            kept.append(r)
    return kept, grids, observed, range_acc, matched


def summarize_scores(scores, counts, label):
    """Correlations with bootstrap intervals plus per-level breakdown."""
    s = np.asarray(scores, dtype=float)
    c = np.asarray(counts, dtype=float)
    r_p = pearson(s, c)
    r_s = spearman(s, c)
    p_lo, p_hi = bootstrap_ci(s, c, pearson)
    s_lo, s_hi = bootstrap_ci(s, c, spearman)
    per_level = {}
    for lv in sorted(set(int(v) for v in c)):
        m = c == lv
        per_level[str(lv)] = {
            "n": int(m.sum()),
            "mean_score": float(s[m].mean()),
            "median_score": float(np.median(s[m])),
            "std_score": float(s[m].std()),
        }
    keys = sorted(per_level, key=int)
    monotonic = all(
        per_level[a]["mean_score"] <= per_level[b]["mean_score"]
        for a, b in zip(keys, keys[1:])
    )
    return {
        "label": label,
        "n": int(s.size),
        "pearson_r": r_p,
        "pearson_ci95": [p_lo, p_hi],
        "spearman_rho": r_s,
        "spearman_ci95": [s_lo, s_hi],
        "per_count_level": per_level,
        "monotonic_in_count": bool(monotonic),
    }


def print_summary(sm, warnings):
    print(f"\n  {sm['label']}  (n={sm['n']:,})")
    print(
        f"    Pearson  r   : {sm['pearson_r']:.3f}   95% CI "
        f"[{sm['pearson_ci95'][0]:.3f}, {sm['pearson_ci95'][1]:.3f}]"
    )
    print(
        f"    Spearman rho : {sm['spearman_rho']:.3f}   95% CI "
        f"[{sm['spearman_ci95'][0]:.3f}, {sm['spearman_ci95'][1]:.3f}]"
    )
    print(f"    monotonic in count: {sm['monotonic_in_count']}")
    print(f"    {'count':>6} {'n':>7} {'mean':>10} {'median':>10} {'std':>10}")
    for lv in sorted(sm["per_count_level"], key=int):
        v = sm["per_count_level"][lv]
        print(
            f"    {lv:>6} {v['n']:>7,} {v['mean_score']:>10.4f} "
            f"{v['median_score']:>10.4f} {v['std_score']:>10.4f}"
        )
    for w in warnings:
        print(f"    FRAGILE: {w}")


def build_arg_parser(default_mode: str) -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        description="Geometric BEV occupancy from stereo depth (CPU, no training)"
    )
    ap.add_argument("--mode", choices=["single", "multi"], default=default_mode)
    ap.add_argument(
        "--camera", default="front_left_color", help="colour timebase camera"
    )
    ap.add_argument("--mirror", choices=sorted(MIRRORS), default="hf")
    ap.add_argument("--data", default=None, help="reuse an existing subset dir")
    ap.add_argument("--no-fetch", action="store_true")
    ap.add_argument(
        "--dry-run", action="store_true", help="report the selection, fetch nothing"
    )
    ap.add_argument("--stride", type=int, default=10)
    ap.add_argument("--max-images", type=int, default=0)
    ap.add_argument("--max-frames", type=int, default=0)
    ap.add_argument(
        "--label-column", default="count_cabin", choices=["count_view", "count_cabin"]
    )
    ap.add_argument("--score-threshold", type=float, default=0.0)
    ap.add_argument(
        "--min-range", type=float, default=0.3, help="D435i lower spec bound (m)"
    )
    ap.add_argument(
        "--max-range", type=float, default=3.0, help="D435i upper spec bound (m)"
    )
    ap.add_argument("--pixel-stride", type=int, default=4)
    ap.add_argument("--cell-size", type=float, default=0.10)
    ap.add_argument("--z-min", type=float, default=0.6)
    ap.add_argument("--z-max", type=float, default=2.0)
    ap.add_argument("--min-points-per-cell", type=int, default=3)
    ap.add_argument("--background-quantile", type=float, default=0.5)
    ap.add_argument("--depth-tolerance-ms", type=int, default=100)
    ap.add_argument("--region-dilate-m", type=float, default=0.30)
    ap.add_argument("--coverage-threshold", type=float, default=0.98)
    ap.add_argument(
        "--continue-on-gap",
        action="store_true",
        help="carry on scoring even if the rig leaves occupied floor unseen",
    )
    ap.add_argument("--out", default=None)
    return ap


def main(default_mode: str = "single", argv=None) -> int:
    args = build_arg_parser(default_mode).parse_args(argv)
    t_start = time.time()
    work_out = "/kaggle/working" if on_kaggle() else "."
    out_path = args.out or os.path.join(
        work_out, f"depth_occupancy_{args.mode}_metrics.json"
    )

    print("=" * 72)
    print(f"Sanas depth occupancy - mode: {args.mode.upper()} (CPU, no training)")
    print("=" * 72)

    diagnostic = report_mounted_kernel_source()

    work, fetch_info = ensure_subset(args)

    depth_cams = (
        [c.replace("_color", "_depth") for c in COLOR_CAMERAS]
        if args.mode == "multi"
        else [args.camera.replace("_color", "_depth")]
    )
    print("\nrig:")
    rig = build_rig(work, depth_cams)

    with open(os.path.join(work, "labels.jsonl"), encoding="utf-8") as fh:
        rows = [json.loads(x) for x in fh if x.strip()]
    rows = [r for r in rows if r.get(args.label_column) is not None]
    if args.max_frames:
        rows = rows[: args.max_frames]
    print(f"\nframes with a {args.label_column} label: {len(rows):,}")
    print(f"count distribution: {count_distribution(rows, args.label_column)}")

    cfg = GridConfig(
        cell_size=args.cell_size,
        z_min=args.z_min,
        z_max=args.z_max,
        min_points_per_cell=args.min_points_per_cell,
    )
    print(
        f"BEV grid {cfg.shape[0]}x{cfg.shape[1]} cells of {cfg.cell_size} m, "
        f"z {cfg.z_min}-{cfg.z_max} m"
    )

    kept, grids, observed, range_acc, matched = score_frames(rows, work, rig, cfg, args)
    print(
        f"\nframes scored: {len(kept):,}   matched depth frames per camera: {matched}"
    )
    if not kept:
        print("nothing to score", file=sys.stderr)
        return 1

    # ---- depth range reality check ------------------------------------
    print("\nDEPTH RANGE REALITY CHECK (share of pixels, mean over frames)")
    range_summary = {}
    for cam, acc in range_acc.items():
        if not acc:
            continue
        agg = {k: float(np.mean([a[k] for a in acc])) for k in acc[0] if k != "pixels"}
        range_summary[cam] = agg
        print(
            f"  {cam:<20} zero {100 * agg['frac_zero']:4.1f}%  "
            f"in {args.min_range}-{args.max_range}m {100 * agg['frac_in_range']:4.1f}%  "
            f"beyond {100 * agg['frac_beyond_max']:4.1f}%"
        )
    worst = min((v["frac_in_range"] for v in range_summary.values()), default=1.0)
    if worst < 0.5:
        print(
            "  VERDICT: on at least one camera most of the frame lies outside the\n"
            "  sensor's reliable window. These scores describe the NEAR FIELD ONLY."
        )

    # ---- step 1: geometric floor coverage on empty-cabin frames --------
    zero_rows = [r for r in kept if int(r[args.label_column]) == 0]
    print(f"\nSTEP 1: FLOOR COVERAGE (empty-cabin frames: {len(zero_rows):,})")
    if not zero_rows:
        print(
            "  no empty-cabin frames; cannot build a background or measure coverage",
            file=sys.stderr,
        )
        return 1

    region = person_region_cells(
        os.path.join(work, "bboxes_3d"), cfg, dilate_m=args.region_dilate_m
    )
    per_cam_obs = {}
    for cam in rig:
        obs = [
            observed[cam][int(r["timestamp"])]
            for r in zero_rows
            if int(r["timestamp"]) in observed[cam]
        ]
        per_cam_obs[cam] = merge_grids(obs) if obs else np.zeros(cfg.shape, dtype=bool)
    cov = coverage_report(per_cam_obs, region)

    print(
        f"  occupied-region cells (from every 3D box, dilated {args.region_dilate_m} m): "
        f"{cov['region_cells']:,}"
    )
    for cam, v in cov["per_camera"].items():
        print(f"    {cam:<20} covers {100 * v['region_fraction']:5.1f}% of the region")
    print(
        f"  UNION of {len(rig)} camera(s): {100 * cov['coverage_fraction']:.1f}% covered, "
        f"{cov['uncovered_cells']:,} cells unseen"
    )

    blocked = (
        args.mode == "multi" and cov["coverage_fraction"] < args.coverage_threshold
    )
    if blocked and not args.continue_on_gap:
        print("\n" + "!" * 72)
        print("RESULT: BLOCKED - four cameras still leave occupied floor unseen.")
        print(
            f"  covered {100 * cov['coverage_fraction']:.1f}% of the region people "
            f"actually occupy; {cov['uncovered_cells']:,} cells have no depth return\n"
            f"  from any camera within {args.min_range}-{args.max_range} m."
        )
        print("  Merged-BEV occupancy over an incompletely observed floor would")
        print("  understate occupancy in a way that looks like a model error rather")
        print("  than a sensing gap, so scoring stops here as instructed.")
        print("  Re-run with --continue-on-gap to score anyway, or raise --max-range")
        print("  (at the cost of trusting depth the sensor is not specified for).")
        print("!" * 72)
        payload = {
            "branch": "depth_geometric_bev",
            "mode": args.mode,
            "trained": False,
            "status": "blocked_incomplete_floor_coverage",
            "coverage": cov,
            "range_summary": range_summary,
            "frames_scored": len(kept),
            "diagnostic_kernel_source_mount": diagnostic,
        }
        with open(out_path, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
        print(f"\nwrote {out_path}")
        return 0

    # ---- step 2: merged BEV + step 3: correlation ----------------------
    print("\nSTEP 2/3: OCCUPANCY SCORES vs GROUND TRUTH")
    backgrounds = {
        cam: build_background(
            [
                grids[cam][int(r["timestamp"])]
                for r in zero_rows
                if int(r["timestamp"]) in grids[cam]
            ],
            args.background_quantile,
        )
        for cam in rig
    }
    merged_background = merge_grids(list(backgrounds.values()))

    counts, per_cam_scores, merged_scores = [], {cam: [] for cam in rig}, []
    for r in kept:
        ts = int(r["timestamp"])
        counts.append(int(r[args.label_column]))
        frame_grids = []
        for cam in rig:
            g = grids[cam].get(ts)
            if g is None:
                g = np.zeros(cfg.shape, dtype=bool)
            frame_grids.append(g)
            s, _ = occupancy_score(g, backgrounds[cam])
            per_cam_scores[cam].append(s)
        ms, _ = occupancy_score(merge_grids(frame_grids), merged_background)
        merged_scores.append(ms)

    warnings = fragility_warnings(np.array(counts))
    summaries = {}
    for cam in rig:
        sm = summarize_scores(per_cam_scores[cam], counts, f"single camera: {cam}")
        summaries[cam] = sm
        print_summary(sm, warnings)
    merged_summary = summarize_scores(
        merged_scores, counts, f"merged {len(rig)} camera(s)"
    )
    print_summary(merged_summary, warnings)

    # ---- step 4: head to head -----------------------------------------
    head_to_head = None
    if args.mode == "multi":
        base_cam = args.camera.replace("_color", "_depth")
        base = summaries.get(base_cam)
        print("\nSTEP 4: 1 CAMERA vs 4 CAMERAS")
        if base:
            d_rho = merged_summary["spearman_rho"] - base["spearman_rho"]
            print(
                f"  {base_cam:<22} Spearman {base['spearman_rho']:.3f} "
                f"CI [{base['spearman_ci95'][0]:.3f}, {base['spearman_ci95'][1]:.3f}]"
            )
            print(
                f"  {'merged 4 cameras':<22} Spearman {merged_summary['spearman_rho']:.3f} "
                f"CI [{merged_summary['spearman_ci95'][0]:.3f}, {merged_summary['spearman_ci95'][1]:.3f}]"
            )
            print(f"  difference: {d_rho:+.3f}")
            overlap = not (
                merged_summary["spearman_ci95"][0] > base["spearman_ci95"][1]
                or base["spearman_ci95"][0] > merged_summary["spearman_ci95"][1]
            )
            print(
                "  the two intervals OVERLAP, so this run does not establish that four\n"
                "  cameras beat one"
                if overlap
                else "  the intervals are disjoint, which is weak evidence of a real difference"
            )
            head_to_head = {
                "baseline_camera": base_cam,
                "baseline_spearman": base["spearman_rho"],
                "merged_spearman": merged_summary["spearman_rho"],
                "difference": d_rho,
                "confidence_intervals_overlap": bool(overlap),
            }

    # ---- step 5: what this does and does not test ----------------------
    scope = [
        "This measures GEOMETRY AND INFRASTRUCTURE: whether the rig sees the floor,",
        "whether depth deprojects into a coherent cabin frame, and whether a BEV",
        "occupancy score moves with occupant count at all.",
        "It does NOT test behaviour in a genuinely full cabin. The dataset never",
        "exceeds 4 occupants and this subset tops out lower, so the crowded regime",
        "that the product exists to measure is entirely unobserved.",
        "Ground truth is model-generated pseudo-labels, not human annotation.",
        "Single 32-minute daytime session: nothing here speaks to low light.",
    ]
    print("\nSTEP 5: SCOPE")
    for line in scope:
        print("  " + line)
    if warnings:
        print("\n  Statistical fragility:")
        for w in warnings:
            print("   - " + w)
        print(
            "  Correlation point estimates above are reported with bootstrap intervals\n"
            "  precisely because the point estimate alone would look more solid than it is."
        )

    payload = {
        "branch": "depth_geometric_bev",
        "mode": args.mode,
        "trained": False,
        "status": "scored",
        "label_column": args.label_column,
        "frames_scored": len(kept),
        "matched_depth_frames": matched,
        "cameras": list(rig),
        "frame_resolved": {c: rig[c]["frame_resolved"] for c in rig},
        "range_gate_m": [args.min_range, args.max_range],
        "range_summary": range_summary,
        "grid": {
            "cell_size": cfg.cell_size,
            "shape": list(cfg.shape),
            "z_min": cfg.z_min,
            "z_max": cfg.z_max,
            "min_points_per_cell": cfg.min_points_per_cell,
        },
        "coverage": cov,
        "coverage_blocked": bool(blocked),
        "background_frames": len(zero_rows),
        "per_camera": summaries,
        "merged": merged_summary,
        "head_to_head": head_to_head,
        "fragility_warnings": warnings,
        "scope": scope,
        "diagnostic_kernel_source_mount": diagnostic,
        "fetch": {k: v for k, v in fetch_info.items() if k != "selection"},
        "seconds": round(time.time() - t_start, 1),
    }
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
    print(f"\nwrote {out_path}")
    print("=" * 72)
    return 0

# <<< SANAS-VENDOR


if __name__ == "__main__":
    raise SystemExit(main(default_mode="multi"))
