#!/usr/bin/env python
"""PHASE 2 KERNEL - DORMANT, NOT DEAD. Do not delete, do not push yet.

Phase 1 is door-mounted APC counting on PCDS: depth geometry and tracking, no
learned model, CPU only. This kernel is the Phase 2 model - RGB whole-frame
cabin classification - and activates once real-bus camera permission lands.
It trains src/sanas/models.py with the src/sanas/corn.py head; all three carry
the same dormant marker so the model and the thing that trains it stay
consistent. Dormant, not gone.

Sanas branch 1: frozen backbone + CORN ordinal head, 1-epoch smoke test.

NEEDS GPU. Burns weekly Kaggle quota, so it does not run until Diyas approves.

What this is: a plumbing check that labels survive extraction and that an
ordinal head can be trained on them. It is NOT a claim about real bus
performance. The substitute dataset never contains more than four occupants
and was recorded in a single 32-minute daytime session, so nothing here
transfers to a crowded or night-time cabin.

Target: RAW COUNT (0-4). No 0-1 normalisation and no 5-level mapping yet, per
the decision recorded in experiments/log.md. Switching to a normalised target
later is a config change: pass --target-mode normalized --capacity N and the
head width, loss and decoder all follow from TargetConfig.

Backbones (both permissively licensed, checked 2026-08-09):
  dinov2_vits14  timm vit_small_patch14_dinov2.lvd142m, Apache-2.0 code+weights
  convnext_tiny  timm convnext_tiny.fb_in1k, MIT / Apache-2.0  (edge comparison)

Prints the train/val split sizes and the count distribution it actually sees,
so the labels can be confirmed end to end.

NOTE ON DUPLICATION: canonical implementations are src/sanas/{config,corn,
models,data}.py. Kaggle pushes one file per kernel, so this is a self-contained
vendored copy. Change src/ first, then re-sync the marked block.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import time
from dataclasses import dataclass, field

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import DataLoader, Dataset

# >>> SANAS-VENDOR: ziprange, selection, labels, fetch, config, corn, models, data
# GENERATED by scripts/build_kernels.py from src/sanas/ - do not edit here.
# Edit the module in src/sanas/, then re-run the generator.

# ---- src/sanas/ziprange.py ----------------------------------------
import json
import os
import struct
import sys
import time
import urllib.error
import urllib.request
import zlib
from dataclasses import asdict, dataclass

MIRRORS = {
    "hf": (
        "https://huggingface.co/datasets/evgenygorelik96/"
        "multiview_incabin_dataset/resolve/main/beintelli_v1.zip"
    ),
    "zenodo": "https://zenodo.org/api/records/20559664/files/beintelli_v1.zip/content",
}
DEFAULT_MIRROR = "hf"

ARCHIVE_NAME = "beintelli_v1.zip"
ARCHIVE_SIZE = 73_515_214_805
ARCHIVE_MD5 = "74924b5be59e706a5a89affba48f6b87"
ROOT_PREFIX = "beintelli_v1/"

# A local file header is 30 bytes + filename + extra field. The central
# directory does not record the *local* extra length, so a run's end is an
# estimate. Padding by the legal maximum (65535) would waste ~25% of the
# transfer on a stride-10 selection, so pad small and let the reader re-fetch
# exactly when a member turns out to overrun its run. Observed local extra
# length in this archive is 32 bytes.
_LOCAL_EXTRA_PAD = 1024

_USER_AGENT = "sanas-occupancy/0.1 (+research; contact via project repo)"


# --------------------------------------------------------------------------
# HTTP
# --------------------------------------------------------------------------


def http_get(
    url: str,
    start: int | None = None,
    end: int | None = None,
    retries: int = 5,
    timeout: int = 120,
    backoff: float = 2.0,
) -> bytes:
    """GET url, optionally a byte range (inclusive bounds), with retries."""
    headers = {"User-Agent": _USER_AGENT}
    if start is not None:
        headers["Range"] = f"bytes={start}-{'' if end is None else end}"
    last: Exception | None = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                if start is not None and resp.status != 206:
                    raise OSError(
                        f"server ignored Range (status {resp.status}); "
                        "mirror does not support partial download"
                    )
                return resp.read()
        except Exception as exc:  # noqa: BLE001 - retry on anything transient
            last = exc
            if attempt == retries - 1:
                break
            time.sleep(backoff**attempt)
    raise OSError(f"GET failed after {retries} attempts: {url} ({last})")


def remote_size(url: str, timeout: int = 60) -> int:
    """Content-Length of the remote archive."""
    req = urllib.request.Request(
        url, method="HEAD", headers={"User-Agent": _USER_AGENT}
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return int(resp.headers["Content-Length"])


# --------------------------------------------------------------------------
# Central directory
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Member:
    """One entry of the ZIP central directory."""

    name: str
    method: int  # 0 = stored, 8 = deflate
    size: int  # uncompressed
    csize: int  # compressed
    offset: int  # local header offset
    crc: int

    @property
    def is_dir(self) -> bool:
        return self.name.endswith("/")


def _find_eocd(tail: bytes) -> tuple[int, int, int]:
    """Return (entry_count, cd_size, cd_offset) from the ZIP tail."""
    i = tail.rfind(b"PK\x05\x06")
    if i == -1:
        raise ValueError("end-of-central-directory record not found in tail")
    _, _, _, _, n, cd_size, cd_off, _ = struct.unpack("<IHHHHIIH", tail[i : i + 22])

    j = tail.rfind(b"PK\x06\x06")
    if j != -1:
        z = struct.unpack("<IQHHIIQQQQ", tail[j : j + 56])
        n, cd_size, cd_off = z[7], z[8], z[9]
    if cd_off == 0xFFFFFFFF:
        raise ValueError("ZIP64 locator required but not found")
    return n, cd_size, cd_off


def parse_central_directory(blob: bytes) -> list[Member]:
    """Parse a raw central directory into Member records (ZIP64 aware)."""
    members: list[Member] = []
    off = 0
    end = len(blob)
    while off + 46 <= end:
        if blob[off : off + 4] != b"PK\x01\x02":
            break
        (
            _sig,
            _vmb,
            _vnb,
            _flags,
            method,
            _mtime,
            _mdate,
            crc,
            csize,
            usize,
            nlen,
            elen,
            clen,
            _dstart,
            _iattr,
            _eattr,
            lhoff,
        ) = struct.unpack("<IHHHHHHIIIHHHHHII", blob[off : off + 46])

        name = blob[off + 46 : off + 46 + nlen].decode("utf-8", "replace")
        extra = blob[off + 46 + nlen : off + 46 + nlen + elen]

        # ZIP64 extended information overrides the 0xFFFFFFFF sentinels.
        eo = 0
        while eo + 4 <= len(extra):
            hid, hsz = struct.unpack("<HH", extra[eo : eo + 4])
            body = extra[eo + 4 : eo + 4 + hsz]
            if hid == 0x0001:
                bo = 0
                if usize == 0xFFFFFFFF and bo + 8 <= len(body):
                    usize = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
                if csize == 0xFFFFFFFF and bo + 8 <= len(body):
                    csize = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
                if lhoff == 0xFFFFFFFF and bo + 8 <= len(body):
                    lhoff = struct.unpack("<Q", body[bo : bo + 8])[0]
                    bo += 8
            eo += 4 + hsz

        members.append(Member(name, method, usize, csize, lhoff, crc))
        off += 46 + nlen + elen + clen
    return members


def read_members(url: str, verbose: bool = True) -> tuple[int, list[Member]]:
    """Fetch and parse the central directory. Downloads ~45 MB, not the archive.

    Returns (archive_size, members). This is the form the kernels use;
    build_index() wraps it for the on-disk index artifact.
    """
    total = remote_size(url)
    if verbose:
        print(f"archive size: {total:,} bytes", flush=True)

    tail = http_get(url, total - 65_536, total - 1)
    n_entries, cd_size, cd_off = _find_eocd(tail)
    if verbose:
        print(
            f"central directory: {n_entries:,} entries, "
            f"{cd_size:,} bytes at offset {cd_off:,}",
            flush=True,
        )

    blob = http_get(url, cd_off, cd_off + cd_size - 1)
    members = parse_central_directory(blob)
    if len(members) != n_entries:
        print(
            f"WARNING: parsed {len(members)} entries, EOCD claims {n_entries}",
            file=sys.stderr,
        )

    return total, members


def build_index(url: str, verbose: bool = True) -> dict:
    """Serialisable index for the on-disk artifact (scripts/build_zip_index.py)."""
    total, members = read_members(url, verbose=verbose)
    return {
        "archive": ARCHIVE_NAME,
        "archive_size": total,
        "archive_md5": ARCHIVE_MD5 if total == ARCHIVE_SIZE else None,
        "source_url": url,
        "entry_count": len(members),
        "members": [asdict(m) for m in members],
    }


def save_index(path: str, index: dict) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(index, fh)


def load_index(path: str) -> tuple[dict, list[Member]]:
    with open(path, encoding="utf-8") as fh:
        index = json.load(fh)
    return index, [Member(**m) for m in index["members"]]


# --------------------------------------------------------------------------
# Extraction
# --------------------------------------------------------------------------


def sniff_image_ext(data: bytes) -> str | None:
    """Return the real extension for an image payload, or None if unknown.

    The dataset's depth frames are named ``*.jpg`` but are actually PNG
    (magic 89 50 4E 47). Anything decoding by extension will mislabel them.
    """
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return ".png"
    if data[:2] == b"\xff\xd8":
        return ".jpg"
    return None


def _run_end(member: Member, archive_size: int) -> int:
    """Exclusive upper bound on the bytes a member can occupy."""
    return min(
        archive_size,
        member.offset
        + 30
        + len(member.name.encode())
        + _LOCAL_EXTRA_PAD
        + member.csize,
    )


def plan_runs(
    members: list[Member],
    archive_size: int,
    gap_merge: int = 1 << 20,
    max_run_bytes: int = 256 << 20,
) -> list[tuple[int, int, list[Member]]]:
    """Group members into contiguous byte runs to keep the request count sane.

    Fetching 130k tiny annotation files one request each is not viable; the
    annotation directories are physically contiguous at the end of the archive
    so they collapse into a handful of runs.
    """
    ordered = sorted((m for m in members if not m.is_dir), key=lambda m: m.offset)
    runs: list[tuple[int, int, list[Member]]] = []
    for m in ordered:
        m_end = _run_end(m, archive_size)
        if runs:
            start, end, group = runs[-1]
            if m.offset - end <= gap_merge and (m_end - start) <= max_run_bytes:
                group.append(m)
                runs[-1] = (start, max(end, m_end), group)
                continue
        runs.append((m.offset, m_end, [m]))
    return runs


def _member_data(buf: bytes, member: Member, base: int, url: str) -> tuple[bytes, int]:
    """Slice one member out of a run buffer and decompress it.

    Falls back to an exact range request for whatever the run buffer did not
    cover, so the run-end estimate never has to be conservative. Returns
    (data, extra_requests).
    """
    extra = 0
    pos = member.offset - base
    if pos < 0 or pos + 30 > len(buf):
        header = http_get(url, member.offset, member.offset + 29)
        extra += 1
    else:
        header = buf[pos : pos + 30]

    sig, _ver, _flg, _meth, _t, _d, _crc, _c, _u, nlen, elen = struct.unpack(
        "<IHHHHHIIIHH", header
    )
    if sig != 0x04034B50:
        raise ValueError(f"bad local header signature for {member.name}")

    data_start = member.offset + 30 + nlen + elen
    lo = data_start - base
    if lo >= 0 and lo + member.csize <= len(buf):
        raw = buf[lo : lo + member.csize]
    else:
        raw = http_get(url, data_start, data_start + member.csize - 1)
        extra += 1
    if len(raw) != member.csize:
        raise ValueError(f"short read for {member.name}")

    data = zlib.decompress(raw, -15) if member.method == 8 else raw
    if member.crc and zlib.crc32(data) & 0xFFFFFFFF != member.crc:
        raise ValueError(f"CRC mismatch for {member.name}")
    return data, extra


def extract_members(
    url: str,
    members: list[Member],
    out_dir: str,
    archive_size: int = ARCHIVE_SIZE,
    strip_prefix: str = ROOT_PREFIX,
    gap_merge: int = 1 << 20,
    max_run_bytes: int = 256 << 20,
    fix_image_extensions: bool = True,
    verbose: bool = True,
) -> dict:
    """Download and inflate the given members into out_dir.

    Returns a summary dict. Members are written at their archive-relative
    path with ``strip_prefix`` removed. When ``fix_image_extensions`` is set,
    a file whose payload disagrees with its extension is written with the
    correct one (this is what handles the depth-frames-are-PNG problem).
    """
    runs = plan_runs(members, archive_size, gap_merge, max_run_bytes)
    planned = sum(end - start for start, end, _ in runs)
    if verbose:
        print(
            f"extracting {len(members):,} members in {len(runs):,} range request(s); "
            f"~{planned / 1e9:.3f} GB to transfer",
            flush=True,
        )

    written = 0
    bytes_out = 0
    extra_requests = 0
    renamed: list[tuple[str, str]] = []
    t0 = time.time()

    for idx, (start, end, group) in enumerate(runs, 1):
        buf = http_get(url, start, end - 1)
        for m in group:
            data, extra = _member_data(buf, m, start, url)
            extra_requests += extra
            rel = (
                m.name[len(strip_prefix) :]
                if m.name.startswith(strip_prefix)
                else m.name
            )
            if fix_image_extensions:
                stem, ext = os.path.splitext(rel)
                real = sniff_image_ext(data[:8])
                if (
                    real
                    and ext.lower() in {".jpg", ".jpeg", ".png"}
                    and real != ext.lower()
                ):
                    renamed.append((rel, stem + real))
                    rel = stem + real
            dst = os.path.join(out_dir, rel.replace("/", os.sep))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            with open(dst, "wb") as fh:
                fh.write(data)
            written += 1
            bytes_out += len(data)
        if verbose and (idx % 25 == 0 or idx == len(runs)):
            rate = planned / max(time.time() - t0, 1e-6) / 1e6
            print(
                f"  run {idx}/{len(runs)}  files={written:,}  "
                f"out={bytes_out / 1e9:.3f} GB  ~{rate:.1f} MB/s",
                flush=True,
            )

    if renamed and verbose:
        print(
            f"  corrected {len(renamed)} file extension(s) after magic-byte sniff "
            f"(e.g. {renamed[0][0]} -> {renamed[0][1]})",
            flush=True,
        )

    return {
        "members": written,
        "bytes_written": bytes_out,
        "bytes_transferred_planned": planned,
        "runs": len(runs),
        "extra_requests": extra_requests,
        "renamed": renamed[:50],
        "renamed_total": len(renamed),
        "seconds": round(time.time() - t0, 1),
    }

# ---- src/sanas/selection.py ---------------------------------------
import bisect
import os
from dataclasses import dataclass, field

ROOT_PREFIX = "beintelli_v1/"

ROOT_METADATA = {
    ROOT_PREFIX + "person_states.json",
    ROOT_PREFIX + "modalities.json",
    ROOT_PREFIX + "frame_ids.json",
    ROOT_PREFIX + "target_transforms.json",
}

COLOR_CAMERAS = [
    "front_left_color",
    "front_right_color",
    "center_left_color",
    "back_right_color",
]

NS_PER_MS = 1_000_000

# What the already-executed single-camera extraction produced. Any change to
# selection logic that moves these numbers is drift and must be deliberate.
SINGLE_CAMERA_EXPECTATION = {
    "images": 1289,
    "depth": 1204,
    "labels": 32911,
    "total_members": 35404,
}


@dataclass
class SubsetSpec:
    """Which archive members a run wants."""

    color_cameras: list = field(default_factory=lambda: ["front_left_color"])
    # Depth streams to pull. None -> the depth twin of each colour camera.
    depth_cameras: list | None = None
    # Colour camera whose frame times define the sampling grid. All depth
    # streams are matched to these instants so the cameras stay in sync.
    timebase_camera: str | None = None
    stride: int = 10
    max_images: int = 0
    include_depth: bool = True
    include_masks: bool = False
    include_poses: bool = False
    depth_tolerance_ms: int = 100

    def resolved_depth_cameras(self) -> list:
        if self.depth_cameras is not None:
            return list(self.depth_cameras)
        if not self.include_depth:
            return []
        return [c.replace("_color", "_depth") for c in self.color_cameras]

    def resolved_timebase(self) -> str:
        return self.timebase_camera or self.color_cameras[0]


def timestamp_of(name: str) -> int | None:
    """19-digit nanosecond stamp from a member name, or None."""
    stem = os.path.splitext(os.path.basename(name))[0].split("_")[0]
    return int(stem) if stem.isdigit() and len(stem) == 19 else None


def nearest(ts: int, sorted_ts: list, tolerance_ns: int) -> int | None:
    if not sorted_ts:
        return None
    i = bisect.bisect_left(sorted_ts, ts)
    best = None
    for j in (i - 1, i):
        if 0 <= j < len(sorted_ts):
            d = abs(sorted_ts[j] - ts)
            if d <= tolerance_ns and (best is None or d < abs(best - ts)):
                best = sorted_ts[j]
    return best


def select_members(members, spec: SubsetSpec):
    """Return (selected_members, breakdown_dict) for a SubsetSpec."""
    timebase = spec.resolved_timebase()
    depth_cams = spec.resolved_depth_cameras()

    # ---- colour frames -------------------------------------------------
    images = []
    per_camera_images = {}
    for cam in spec.color_cameras:
        cam_imgs = sorted(
            (
                m
                for m in members
                if m.name.startswith(f"{ROOT_PREFIX}cameras/color/{cam}/images/")
                and m.name.endswith(".jpg")
            ),
            key=lambda m: m.name,
        )
        picked = cam_imgs[:: spec.stride]
        if spec.max_images:
            picked = picked[: spec.max_images]
        per_camera_images[cam] = picked
        images.extend(picked)

    timebase_ts = [timestamp_of(m.name) for m in per_camera_images.get(timebase, [])]
    timebase_ts = [t for t in timebase_ts if t is not None]

    # ---- annotations ---------------------------------------------------
    seg_prefixes = tuple(f"{ROOT_PREFIX}segmentations/{c}/" for c in spec.color_cameras)
    labels = []
    for m in members:
        n = m.name
        if m.is_dir:
            continue
        if n.startswith(seg_prefixes):
            if n.endswith(".json") or (spec.include_masks and n.endswith(".png")):
                labels.append(m)
        elif n.startswith(f"{ROOT_PREFIX}bboxes_3d/") or n.startswith(
            f"{ROOT_PREFIX}states/"
        ):
            labels.append(m)
        elif spec.include_poses and n.startswith(f"{ROOT_PREFIX}poses/"):
            labels.append(m)
        elif n in ROOT_METADATA:
            labels.append(m)
        elif n.startswith(f"{ROOT_PREFIX}cameras/") and n.endswith("camera_info.yaml"):
            labels.append(m)

    # ---- depth frames, matched to the timebase -------------------------
    depth = []
    per_camera_depth = {}
    tol = spec.depth_tolerance_ms * NS_PER_MS
    for dcam in depth_cams:
        cand = {}
        for m in members:
            if m.is_dir:
                continue
            if not m.name.startswith(f"{ROOT_PREFIX}cameras/depth/{dcam}/images/"):
                continue
            t = timestamp_of(m.name)
            if t is not None:
                cand[t] = m
        keys = sorted(cand)
        seen, chosen = set(), []
        for t in timebase_ts:
            hit = nearest(t, keys, tol)
            if hit is not None and hit not in seen:
                seen.add(hit)
                chosen.append(cand[hit])
        per_camera_depth[dcam] = chosen
        depth.extend(chosen)

    selected = images + labels + depth
    breakdown = {
        "timebase_camera": timebase,
        "stride": spec.stride,
        "images": len(images),
        "image_bytes": sum(m.csize for m in images),
        "labels": len(labels),
        "label_bytes": sum(m.csize for m in labels),
        "depth": len(depth),
        "depth_bytes": sum(m.csize for m in depth),
        "total_members": len(selected),
        "total_compressed_bytes": sum(m.csize for m in selected),
        "per_camera_images": {c: len(v) for c, v in per_camera_images.items()},
        "per_camera_depth": {c: len(v) for c, v in per_camera_depth.items()},
        "per_camera_depth_bytes": {
            c: sum(m.csize for m in v) for c, v in per_camera_depth.items()
        },
    }
    return selected, breakdown


def check_single_camera_regression(breakdown: dict, keys=None) -> list:
    """Compare a single-camera breakdown against what already ran.

    `keys` limits the comparison, because a run that deliberately skips depth
    cannot be expected to match the depth-inclusive frame counts. Returns a
    list of human-readable mismatches; empty means no drift.
    """
    problems = []
    for key, expected in SINGLE_CAMERA_EXPECTATION.items():
        if keys is not None and key not in keys:
            continue
        actual = breakdown.get(key)
        if actual != expected:
            problems.append(f"{key}: expected {expected:,}, got {actual:,}")
    return problems

# ---- src/sanas/labels.py ------------------------------------------
import bisect
import json
import os

NS_PER_MS = 1_000_000


def counts_from_segmentation(
    payload: bytes | str, score_threshold: float = 0.0
) -> tuple[int, float | None]:
    """Return (person_count, min_score) for one segmentation JSON."""
    entries = json.loads(payload)
    if not isinstance(entries, list):
        raise ValueError("segmentation JSON is not a list")
    kept = [e for e in entries if float(e.get("score", 1.0)) >= score_threshold]
    min_score = min((float(e.get("score", 1.0)) for e in kept), default=None)
    return len(kept), min_score


def counts_from_bboxes(payload: bytes | str, label: str = "human") -> int:
    """Return the number of oriented 3D boxes with the given label."""
    entries = json.loads(payload)
    if not isinstance(entries, list):
        raise ValueError("bboxes_3d JSON is not a list")
    return sum(1 for e in entries if e.get("bbox_label") == label)


def _ts_from_filename(path: str) -> int | None:
    stem = os.path.splitext(os.path.basename(path))[0]
    stem = stem.split("_")[0]
    return int(stem) if stem.isdigit() and len(stem) == 19 else None


def load_view_counts(
    subset_dir: str, camera: str, score_threshold: float = 0.0
) -> dict[int, tuple[int, float | None]]:
    """Map camera timestamp -> (count_view, min_score) for one camera."""
    seg_dir = os.path.join(subset_dir, "segmentations", camera)
    out: dict[int, tuple[int, float | None]] = {}
    if not os.path.isdir(seg_dir):
        return out
    for name in os.listdir(seg_dir):
        if not name.endswith(".json"):
            continue
        ts = _ts_from_filename(name)
        if ts is None:
            continue
        with open(os.path.join(seg_dir, name), "rb") as fh:
            out[ts] = counts_from_segmentation(fh.read(), score_threshold)
    return out


def load_cabin_counts(subset_dir: str) -> dict[int, int]:
    """Map lidar timestamp -> total occupants from bboxes_3d."""
    box_dir = os.path.join(subset_dir, "bboxes_3d")
    out: dict[int, int] = {}
    if not os.path.isdir(box_dir):
        return out
    for name in os.listdir(box_dir):
        if not name.endswith(".json"):
            continue
        ts = _ts_from_filename(name)
        if ts is None:
            continue
        with open(os.path.join(box_dir, name), "rb") as fh:
            out[ts] = counts_from_bboxes(fh.read())
    return out


def match_nearest(ts: int, sorted_ts: list[int], tolerance_ns: int) -> int | None:
    """Nearest timestamp in sorted_ts within tolerance, else None."""
    if not sorted_ts:
        return None
    i = bisect.bisect_left(sorted_ts, ts)
    best = None
    for j in (i - 1, i):
        if 0 <= j < len(sorted_ts):
            d = abs(sorted_ts[j] - ts)
            if d <= tolerance_ns and (best is None or d < abs(best - ts)):
                best = sorted_ts[j]
    return best


def assign_sequences(sorted_ts: list[int], gap_ns: int = 5 * 10**9) -> dict[int, int]:
    """Split a timestamp list into sub-sequences at recording gaps.

    Frames are ~0.067 s apart, so a random train/val split leaks near-duplicate
    neighbours across the boundary. The recording has 10 gaps > 5 s in
    front_left_color, giving 11 sub-sequences to split on instead.
    """
    seq: dict[int, int] = {}
    current = 0
    for i, ts in enumerate(sorted_ts):
        if i and ts - sorted_ts[i - 1] > gap_ns:
            current += 1
        seq[ts] = current
    return seq


def build_label_table(
    subset_dir: str,
    camera: str,
    score_threshold: float = 0.0,
    cabin_tolerance_ns: int = 100 * NS_PER_MS,
    sequence_gap_ns: int = 5 * 10**9,
) -> list[dict]:
    """Join extracted images with their counts into one row per frame."""
    img_dir = os.path.join(subset_dir, "cameras", "color", camera, "images")
    if not os.path.isdir(img_dir):
        raise FileNotFoundError(f"no extracted images at {img_dir}")

    images: dict[int, str] = {}
    for name in sorted(os.listdir(img_dir)):
        ts = _ts_from_filename(name)
        if ts is not None:
            images[ts] = f"cameras/color/{camera}/images/{name}"

    view = load_view_counts(subset_dir, camera, score_threshold)
    cabin = load_cabin_counts(subset_dir)
    cabin_ts = sorted(cabin)

    ordered = sorted(images)
    seq = assign_sequences(ordered, sequence_gap_ns)

    rows: list[dict] = []
    for ts in ordered:
        v = view.get(ts)
        c_ts = match_nearest(ts, cabin_ts, cabin_tolerance_ns)
        rows.append(
            {
                "timestamp": ts,
                "camera": camera,
                "image": images[ts],
                "sequence": seq[ts],
                "count_view": None if v is None else v[0],
                "min_score": None if v is None else v[1],
                "count_cabin": None if c_ts is None else cabin[c_ts],
                "cabin_dt_ns": None if c_ts is None else c_ts - ts,
            }
        )
    return rows


def count_distribution(rows: list[dict], column: str) -> dict[str, int]:
    dist: dict[str, int] = {}
    for r in rows:
        key = "missing" if r.get(column) is None else str(r[column])
        dist[key] = dist.get(key, 0) + 1
    return dict(sorted(dist.items(), key=lambda kv: (kv[0] == "missing", kv[0])))


def write_labels(path: str, rows: list[dict]) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")


def read_labels(path: str) -> list[dict]:
    with open(path, encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]

# ---- src/sanas/fetch.py -------------------------------------------
import json
import os
import sys



def default_work_dir() -> str:
    return (
        "/kaggle/working/subset"
        if os.path.isdir("/kaggle/working")
        else os.path.join("data", "subset")
    )


def fetch_subset(
    work: str | None = None,
    mirror: str = "hf",
    camera: str = "front_left_color",
    stride: int = 10,
    max_images: int = 0,
    depth_cameras: list | None = None,
    include_depth: bool = True,
    score_threshold: float = 0.0,
    dry_run: bool = False,
    no_fetch: bool = False,
    check_regression: bool = True,
    verbose: bool = True,
) -> tuple[str, dict]:
    """Ensure a usable subset exists at `work`. Returns (work_dir, info)."""
    work = work or default_work_dir()
    labels_path = os.path.join(work, "labels.jsonl")

    if no_fetch:
        if not os.path.exists(labels_path):
            raise SystemExit(f"--no-fetch given but {labels_path} is missing")
        if verbose:
            print(f"--no-fetch: reusing existing subset at {work}")
        return work, {"fetched": False}

    spec = SubsetSpec(
        color_cameras=[camera],
        depth_cameras=depth_cameras,
        timebase_camera=camera,
        stride=stride,
        max_images=max_images,
        include_depth=include_depth,
    )

    url = MIRRORS[mirror]
    if verbose:
        print(f"mirror: {mirror}")
    archive_size, members = read_members(url, verbose=verbose)
    if archive_size != ARCHIVE_SIZE:
        print(
            f"WARNING: archive is {archive_size:,} bytes, expected {ARCHIVE_SIZE:,}",
            file=sys.stderr,
        )

    selected, breakdown = select_members(members, spec)
    if verbose:
        print("\nselection (shared definition, src/sanas/selection.py):")
        for k in (
            "images",
            "labels",
            "depth",
            "total_members",
            "total_compressed_bytes",
        ):
            print(f"  {k:<26} {breakdown[k]:,}")
        print(f"  {'GB selected':<26} {breakdown['total_compressed_bytes'] / 1e9:.3f}")
        print(f"  per-camera depth frames    {breakdown['per_camera_depth']}")

    single_default = (
        check_regression
        and stride == 10
        and max_images == 0
        and camera == "front_left_color"
        and len(spec.resolved_depth_cameras()) <= 1
    )
    if single_default and verbose:
        keys = (
            ("images", "labels", "depth", "total_members")
            if include_depth
            else ("images", "labels")
        )
        problems = check_single_camera_regression(breakdown, keys=keys)
        print(
            "  regression vs executed run: "
            + ("CLEAN" if not problems else "DRIFT -> " + "; ".join(problems))
        )

    if dry_run:
        runs = plan_runs(selected, archive_size)
        planned = sum(e - s for s, e, _ in runs)
        print(
            f"\n--dry-run: would issue {len(runs):,} range request(s), "
            f"~{planned / 1e9:.3f} GB. Nothing downloaded."
        )
        raise SystemExit(0)

    os.makedirs(work, exist_ok=True)
    stats = extract_members(
        url, selected, work, archive_size=archive_size, verbose=verbose
    )
    if verbose:
        print(
            f"\nextracted {stats['members']:,} files, "
            f"{stats['bytes_written'] / 1e9:.3f} GB in {stats['seconds']}s "
            f"({stats['renamed_total']:,} extensions corrected by magic-byte sniff)"
        )

    rows = build_label_table(work, camera, score_threshold=score_threshold)
    with open(labels_path, "w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")
    if verbose:
        print(f"labels: {len(rows):,} rows -> {labels_path}")
        print(f"count_view  {count_distribution(rows, 'count_view')}")
        print(f"count_cabin {count_distribution(rows, 'count_cabin')}")

    return work, {"fetched": True, "selection": breakdown, "transfer": stats}

# ---- src/sanas/config.py ------------------------------------------
from dataclasses import dataclass, field

RAW_COUNT = "raw_count"
NORMALIZED = "normalized"


@dataclass
class TargetConfig:
    """How a per-frame occupant count becomes a training target.

    mode=raw_count   classes are the counts themselves, 0..max_count.
                     decode() returns a count.
    mode=normalized  counts are bucketed into num_levels ordinal levels by
                     occupancy fraction count/capacity. decode() returns the
                     0-1 density score. Not used yet: needs real crowding data
                     and a decision on `capacity` for the target vehicle.
    """

    mode: str = RAW_COUNT
    label_column: str = "count_view"
    # raw_count
    max_count: int = 4
    # normalized (unused until real crowding data exists)
    capacity: int | None = None
    num_levels: int | None = 5
    level_edges: list[float] = field(default_factory=lambda: [0.2, 0.4, 0.6, 0.8])

    def __post_init__(self) -> None:
        if self.mode not in (RAW_COUNT, NORMALIZED):
            raise ValueError(f"unknown target mode {self.mode!r}")
        if self.mode == NORMALIZED:
            if not self.capacity or self.capacity <= 0:
                raise ValueError("normalized mode needs a positive capacity")
            if not self.num_levels or self.num_levels < 2:
                raise ValueError("normalized mode needs num_levels >= 2")
            if len(self.level_edges) != self.num_levels - 1:
                raise ValueError(
                    f"num_levels={self.num_levels} needs {self.num_levels - 1} "
                    f"level_edges, got {len(self.level_edges)}"
                )

    @property
    def num_classes(self) -> int:
        return self.max_count + 1 if self.mode == RAW_COUNT else int(self.num_levels)

    @property
    def num_thresholds(self) -> int:
        """Width of the CORN head: K-1 binary tasks for K ordered classes."""
        return self.num_classes - 1

    def encode(self, count: int) -> int:
        """Occupant count -> ordinal class index."""
        if self.mode == RAW_COUNT:
            return max(0, min(int(count), self.max_count))
        frac = count / self.capacity
        cls = 0
        for edge in self.level_edges:
            if frac >= edge:
                cls += 1
        return min(cls, self.num_classes - 1)

    def decode(self, cls: int) -> float:
        """Ordinal class index -> reported value.

        raw_count  -> occupant count
        normalized -> 0-1 density score (lower edge of the predicted level)
        """
        cls = max(0, min(int(cls), self.num_classes - 1))
        if self.mode == RAW_COUNT:
            return float(cls)
        edges = [0.0, *self.level_edges]
        return float(edges[cls])

    def describe(self) -> str:
        if self.mode == RAW_COUNT:
            return (
                f"raw_count on '{self.label_column}', classes 0..{self.max_count} "
                f"({self.num_classes} classes, {self.num_thresholds} CORN thresholds)"
            )
        return (
            f"normalized on '{self.label_column}', capacity={self.capacity}, "
            f"{self.num_levels} levels, edges={self.level_edges}"
        )

# ---- src/sanas/corn.py --------------------------------------------
import torch
import torch.nn.functional as F


def corn_loss(
    logits: torch.Tensor, targets: torch.Tensor, num_classes: int
) -> torch.Tensor:
    """Mean CORN loss.

    logits  (N, num_classes - 1) raw scores, one per ordinal threshold
    targets (N,) integer class indices in [0, num_classes - 1]
    """
    if logits.ndim != 2 or logits.shape[1] != num_classes - 1:
        raise ValueError(
            f"expected logits of shape (N, {num_classes - 1}), got {tuple(logits.shape)}"
        )
    targets = targets.long()
    total = logits.new_zeros(())
    used = 0
    for k in range(num_classes - 1):
        # Conditional subset: only samples that got at least this far.
        mask = targets >= k
        if not bool(mask.any()):
            continue
        binary = (targets[mask] > k).float()
        total = total + F.binary_cross_entropy_with_logits(
            logits[mask, k], binary, reduction="mean"
        )
        used += 1
    return total / max(used, 1)


def corn_cumulative_probs(logits: torch.Tensor) -> torch.Tensor:
    """P(y > k) for each threshold k, as the running product of conditionals."""
    return torch.cumprod(torch.sigmoid(logits), dim=1)


def corn_predict(logits: torch.Tensor, threshold: float = 0.5) -> torch.Tensor:
    """Decode logits to integer class indices."""
    return (corn_cumulative_probs(logits) > threshold).sum(dim=1)


def corn_expected_class(logits: torch.Tensor) -> torch.Tensor:
    """Soft class estimate: sum of P(y > k). Useful as a continuous score."""
    return corn_cumulative_probs(logits).sum(dim=1)

# ---- src/sanas/models.py ------------------------------------------
import torch
import torch.nn as nn

BACKBONES = {
    "dinov2_vits14": {
        "timm_name": "vit_small_patch14_dinov2.lvd142m",
        "input_size": 224,  # must be a multiple of the patch size (14)
        "license": "Apache-2.0 (code and weights)",
        "params_m": 21,
    },
    "convnext_tiny": {
        "timm_name": "convnext_tiny.fb_in1k",
        "input_size": 224,
        "license": "MIT (ConvNeXt) / Apache-2.0 (timm)",
        "params_m": 28,
    },
}


class OrdinalHead(nn.Module):
    """LayerNorm + dropout + linear, producing one logit per ordinal threshold."""

    def __init__(self, in_features: int, num_thresholds: int, dropout: float = 0.1):
        super().__init__()
        self.norm = nn.LayerNorm(in_features)
        self.drop = nn.Dropout(dropout)
        self.fc = nn.Linear(in_features, num_thresholds)
        nn.init.zeros_(self.fc.bias)

    def forward(self, feats: torch.Tensor) -> torch.Tensor:
        return self.fc(self.drop(self.norm(feats)))


class FrozenBackboneOrdinal(nn.Module):
    def __init__(self, backbone: nn.Module, head: OrdinalHead, frozen: bool):
        super().__init__()
        self.backbone = backbone
        self.head = head
        self.frozen = frozen

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.frozen:
            with torch.no_grad():
                feats = self.backbone(x)
        else:
            feats = self.backbone(x)
        return self.head(feats.float())

    def trainable_parameters(self):
        return (p for p in self.parameters() if p.requires_grad)


def build_model(
    backbone: str,
    num_thresholds: int,
    pretrained: bool = True,
    freeze: bool = True,
    dropout: float = 0.1,
) -> tuple[FrozenBackboneOrdinal, dict]:
    """Build a frozen-backbone CORN model. Returns (model, backbone_info)."""
    import timm  # imported lazily so the module imports without torch extras

    if backbone not in BACKBONES:
        raise ValueError(
            f"unknown backbone {backbone!r}; choose from {sorted(BACKBONES)}"
        )
    info = dict(BACKBONES[backbone])

    net = timm.create_model(info["timm_name"], pretrained=pretrained, num_classes=0)
    if freeze:
        net.eval()
        for p in net.parameters():
            p.requires_grad_(False)

    dim = getattr(net, "num_features", None)
    if dim is None:
        raise RuntimeError(f"cannot determine feature dim for {info['timm_name']}")

    model = FrozenBackboneOrdinal(
        net, OrdinalHead(dim, num_thresholds, dropout), freeze
    )
    info["feature_dim"] = dim
    info["backbone_key"] = backbone
    info["frozen"] = freeze
    info["trainable_params"] = sum(
        p.numel() for p in model.parameters() if p.requires_grad
    )
    info["total_params"] = sum(p.numel() for p in model.parameters())
    return model, info


def train_mode(model: FrozenBackboneOrdinal) -> None:
    """Put the head in train mode while keeping a frozen backbone in eval.

    Matters: a frozen backbone left in train() would keep updating BatchNorm
    running statistics on ConvNeXt-style models.
    """
    model.train()
    if model.frozen:
        model.backbone.eval()

# ---- src/sanas/data.py --------------------------------------------
import os

import torch
from PIL import Image
from torch.utils.data import Dataset


IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)


def build_transforms(img_size: int, train: bool):
    from torchvision import transforms

    if train:
        # Deliberately mild: no horizontal flip, because cabin geometry is
        # fixed and a mirrored bus interior is not a real input.
        return transforms.Compose(
            [
                transforms.Resize((img_size, img_size)),
                transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2),
                transforms.ToTensor(),
                transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
            ]
        )
    return transforms.Compose(
        [
            transforms.Resize((img_size, img_size)),
            transforms.ToTensor(),
            transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
        ]
    )


class OccupancyCountDataset(Dataset):
    """One extracted frame -> (image tensor, ordinal class, raw count)."""

    def __init__(
        self, root: str, rows: list[dict], target: TargetConfig, transform=None
    ):
        self.root = root
        self.rows = rows
        self.target = target
        self.transform = transform

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, idx: int):
        row = self.rows[idx]
        path = os.path.join(self.root, row["image"].replace("/", os.sep))
        img = Image.open(path).convert("RGB")
        if self.transform is not None:
            img = self.transform(img)
        count = int(row[self.target.label_column])
        cls = self.target.encode(count)
        return (
            img,
            torch.tensor(cls, dtype=torch.long),
            torch.tensor(count, dtype=torch.long),
        )


def usable_rows(rows: list[dict], target: TargetConfig) -> tuple[list[dict], int]:
    """Drop rows without a label. Returns (kept, dropped)."""
    kept = [r for r in rows if r.get(target.label_column) is not None]
    return kept, len(rows) - len(kept)


def split_by_sequence(
    rows: list[dict], val_fraction: float = 0.25, seed: int = 0
) -> tuple[list[dict], list[dict], list[int]]:
    """Hold out whole sub-sequences for validation.

    Returns (train, val, held_out_sequence_ids). Sequences are assigned to val
    largest-first until the target fraction is met, which keeps the split
    deterministic and avoids a val set made only of tiny fragments.
    """
    import random

    by_seq: dict[int, list[dict]] = {}
    for r in rows:
        by_seq.setdefault(int(r["sequence"]), []).append(r)

    seq_ids = sorted(by_seq, key=lambda s: (-len(by_seq[s]), s))
    rng = random.Random(seed)
    rng.shuffle(seq_ids)

    target_n = val_fraction * len(rows)
    val_seqs: set[int] = set()
    running = 0
    for s in seq_ids:
        if running >= target_n:
            break
        val_seqs.add(s)
        running += len(by_seq[s])

    # Never let the split collapse to empty on either side.
    if not val_seqs or len(val_seqs) == len(seq_ids):
        val_seqs = {seq_ids[0]}

    train = [r for r in rows if int(r["sequence"]) not in val_seqs]
    val = [r for r in rows if int(r["sequence"]) in val_seqs]
    return train, val, sorted(val_seqs)

# <<< SANAS-VENDOR


def evaluate(model, loader, target, device):
    model.eval()
    preds, gts, soft = [], [], []
    with torch.no_grad():
        for imgs, cls, _count in loader:
            imgs = imgs.to(device, non_blocking=True)
            logits = model(imgs)
            preds.append(corn_predict(logits).cpu())
            soft.append(corn_expected_class(logits).cpu())
            gts.append(cls)
    if not preds:
        return {}
    p = torch.cat(preds).numpy()
    g = torch.cat(gts).numpy()
    s = torch.cat(soft).numpy()
    n = len(g)
    k = target.num_classes
    cm = np.zeros((k, k), dtype=int)
    for a, b in zip(g, p):
        cm[int(a), int(b)] += 1
    return {
        "n": int(n),
        "exact_match_accuracy": float((p == g).mean()),
        "within_one_accuracy": float((np.abs(p - g) <= 1).mean()),
        "mae_classes": float(np.abs(p - g).mean()),
        "mae_soft": float(np.abs(s - g).mean()),
        "confusion_matrix": cm.tolist(),
        "pred_distribution": {str(i): int((p == i).sum()) for i in range(k)},
    }


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Frozen backbone + CORN ordinal head (1-epoch smoke test)"
    )
    ap.add_argument("--data", default=None, help="subset dir; fetched if absent")
    ap.add_argument("--mirror", choices=sorted(MIRRORS), default="hf")
    ap.add_argument("--camera", default="front_left_color")
    ap.add_argument("--stride", type=int, default=10)
    ap.add_argument("--max-images", type=int, default=0)
    ap.add_argument("--no-fetch", action="store_true", help="reuse an existing subset")
    ap.add_argument(
        "--dry-run", action="store_true", help="report the selection, fetch nothing"
    )
    ap.add_argument("--backbone", default="dinov2_vits14", choices=sorted(BACKBONES))
    ap.add_argument(
        "--compare-backbone",
        default="convnext_tiny",
        help="second backbone to train identically; '' to skip",
    )
    ap.add_argument("--epochs", type=int, default=1)
    ap.add_argument("--batch-size", type=int, default=32)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--weight-decay", type=float, default=1e-4)
    ap.add_argument("--img-size", type=int, default=224)
    ap.add_argument("--workers", type=int, default=2)
    ap.add_argument("--val-fraction", type=float, default=0.25)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--target-mode", default=RAW_COUNT, choices=[RAW_COUNT, NORMALIZED])
    ap.add_argument(
        "--label-column", default="count_view", choices=["count_view", "count_cabin"]
    )
    ap.add_argument("--max-count", type=int, default=4)
    ap.add_argument(
        "--capacity", type=int, default=None, help="only for --target-mode normalized"
    )
    ap.add_argument(
        "--num-levels", type=int, default=5, help="only for --target-mode normalized"
    )
    ap.add_argument("--limit", type=int, default=0, help="cap frames, for debugging")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    random.seed(args.seed)
    np.random.seed(args.seed)

    data, _fetch_info = fetch_subset(
        work=args.data,
        mirror=args.mirror,
        camera=args.camera,
        stride=args.stride,
        max_images=args.max_images,
        include_depth=False,
        score_threshold=0.0,
        dry_run=args.dry_run,
        no_fetch=args.no_fetch,
    )
    work = "/kaggle/working" if os.path.isdir("/kaggle/working") else "."
    out_path = args.out or os.path.join(work, "train_metrics.json")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    target = TargetConfig(
        mode=args.target_mode,
        label_column=args.label_column,
        max_count=args.max_count,
        capacity=args.capacity,
        num_levels=args.num_levels,
    )

    print("=" * 72)
    print("Sanas branch 1: frozen backbone + CORN ordinal head")
    print("=" * 72)
    print(f"data    : {data}")
    print(
        f"device  : {device}  ({torch.cuda.get_device_name(0) if device.type == 'cuda' else 'CPU'})"
    )
    print(f"target  : {target.describe()}")
    print(f"torch   : {torch.__version__}")

    labels_path = os.path.join(data, "labels.jsonl")
    if not os.path.exists(labels_path):
        print(
            f"missing {labels_path}. Run the extraction kernel first.", file=sys.stderr
        )
        return 1
    with open(labels_path, encoding="utf-8") as fh:
        rows = [json.loads(x) for x in fh if x.strip()]

    total_rows = len(rows)
    rows = [r for r in rows if r.get(target.label_column) is not None]
    dropped = total_rows - len(rows)
    if args.limit:
        rows = rows[: args.limit]

    train_rows, val_rows, val_seqs = split_by_sequence(
        rows, args.val_fraction, args.seed
    )

    print("\n" + "-" * 72)
    print("LABELS AS ACTUALLY SEEN BY THE TRAINER")
    print("-" * 72)
    print(f"rows in labels.jsonl      : {total_rows:,}")
    print(f"dropped (no label)        : {dropped:,}")
    print(f"usable                    : {len(rows):,}")
    print(f"sub-sequences             : {len({int(r['sequence']) for r in rows})}")
    print(f"train frames              : {len(train_rows):,}")
    print(
        f"val frames                : {len(val_rows):,}   (held-out sequences {val_seqs})"
    )
    print(
        f"count dist  (all)         : {count_distribution(rows, target.label_column)}"
    )
    print(
        f"count dist  (train)       : {count_distribution(train_rows, target.label_column)}"
    )
    print(
        f"count dist  (val)         : {count_distribution(val_rows, target.label_column)}"
    )
    print(
        f"class dist  (train)       : "
        f"{count_distribution([{'c': target.encode(int(r[target.label_column]))} for r in train_rows], 'c')}"
    )
    print(f"other column (count_cabin): {count_distribution(rows, 'count_cabin')}")
    if not train_rows or not val_rows:
        print("empty split; aborting", file=sys.stderr)
        return 1

    results = {}
    backbones = [args.backbone] + (
        [args.compare_backbone] if args.compare_backbone else []
    )
    for bb in backbones:
        print("\n" + "=" * 72)
        print(f"BACKBONE: {bb}")
        print("=" * 72)
        model, info = build_model(bb, target.num_thresholds)
        model.to(device)
        print(f"  timm name        : {info['timm_name']}")
        print(f"  licence          : {info['license']}")
        print(f"  feature dim      : {info['feature_dim']}")
        print(f"  total params     : {info['total_params']:,}")
        print(f"  trainable params : {info['trainable_params']:,} (head only)")

        tr = DataLoader(
            OccupancyCountDataset(
                data, train_rows, target, build_transforms(args.img_size, True)
            ),
            batch_size=args.batch_size,
            shuffle=True,
            num_workers=args.workers,
            pin_memory=(device.type == "cuda"),
            drop_last=False,
        )
        va = DataLoader(
            OccupancyCountDataset(
                data, val_rows, target, build_transforms(args.img_size, False)
            ),
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.workers,
            pin_memory=(device.type == "cuda"),
        )

        opt = torch.optim.AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=args.lr,
            weight_decay=args.weight_decay,
        )
        scaler = torch.cuda.amp.GradScaler(enabled=(device.type == "cuda"))

        t0 = time.time()
        for epoch in range(args.epochs):
            model.train()
            if model.frozen:
                model.backbone.eval()  # keep frozen BN/stat layers frozen too
            running, seen = 0.0, 0
            for i, (imgs, cls, _c) in enumerate(tr, 1):
                imgs = imgs.to(device, non_blocking=True)
                cls = cls.to(device, non_blocking=True)
                opt.zero_grad(set_to_none=True)
                with torch.cuda.amp.autocast(enabled=(device.type == "cuda")):
                    logits = model(imgs)
                    loss = corn_loss(logits.float(), cls, target.num_classes)
                scaler.scale(loss).backward()
                scaler.step(opt)
                scaler.update()
                running += loss.item() * imgs.size(0)
                seen += imgs.size(0)
                if i % 10 == 0 or i == len(tr):
                    print(
                        f"  epoch {epoch + 1} step {i}/{len(tr)}  loss {running / seen:.4f}",
                        flush=True,
                    )
            print(
                f"  epoch {epoch + 1} done in {time.time() - t0:.0f}s, train loss {running / seen:.4f}"
            )

        metrics = evaluate(model, va, target, device)
        metrics.update(
            backbone=bb,
            timm_name=info["timm_name"],
            license=info["license"],
            trainable_params=info["trainable_params"],
            seconds=round(time.time() - t0, 1),
        )
        print("\n  VALIDATION (held-out sequences)")
        print(f"    exact match      : {metrics['exact_match_accuracy']:.3f}")
        print(f"    within +/-1      : {metrics['within_one_accuracy']:.3f}")
        print(f"    MAE (classes)    : {metrics['mae_classes']:.3f}")
        print(f"    MAE (soft score) : {metrics['mae_soft']:.3f}")
        print(f"    pred dist        : {metrics['pred_distribution']}")
        print("    confusion (rows=true, cols=pred):")
        for r_i, row in enumerate(metrics["confusion_matrix"]):
            print(f"      {r_i}: {row}")
        results[bb] = metrics

        torch.save(
            {
                "head": model.head.state_dict(),
                "backbone": bb,
                "target": target.__dict__,
            },
            os.path.join(work, f"head_{bb}.pt"),
        )

    payload = {
        "branch": "rgb_frozen_backbone_corn",
        "trained": True,
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "img_size": args.img_size,
        "target": target.__dict__,
        "data_dir": data,
        "frames_total": total_rows,
        "frames_used": len(rows),
        "train_frames": len(train_rows),
        "val_frames": len(val_rows),
        "val_sequences": val_seqs,
        "count_distribution_all": count_distribution(rows, target.label_column),
        "count_distribution_train": count_distribution(train_rows, target.label_column),
        "count_distribution_val": count_distribution(val_rows, target.label_column),
        "results": results,
        "caveats": [
            "Pipeline check only, not a claim about real bus performance.",
            "Max 4 occupants anywhere in this dataset; upper occupancy levels have zero examples.",
            "Single 32-minute daytime session: low-light robustness is untestable here.",
            "Ground truth is model-generated pseudo-labels, not human annotation.",
        ],
    }
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
    print(f"\nwrote {out_path}")
    print("=" * 72)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
