#!/usr/bin/env python
"""Generate the vendored code blocks inside the Kaggle kernel scripts.

Kaggle pushes ONE file per kernel and nothing is uploaded alongside it, so
each kernel has to be self-contained. Hand-copying shared logic into four
kernels is how the 1-camera and 4-camera runs would quietly drift apart and
start measuring our own inconsistency instead of measuring cameras.

So: development/src/sanas/ is the single source of truth, and this script inlines the
requested modules into each kernel between markers.

    # >>> SANAS-VENDOR: ziprange, selection
    ...generated, do not edit...
    # <<< SANAS-VENDOR

Usage:
    python development/scripts/build_kernels.py            # regenerate in place
    python development/scripts/build_kernels.py --check    # fail if any kernel is stale

--check is the drift detector: run it before pushing.
"""

from __future__ import annotations

import argparse
import ast
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "src", "sanas")
BEGIN = "# >>> SANAS-VENDOR:"
END = "# <<< SANAS-VENDOR"

KERNELS = [
    os.path.join(REPO, "notebooks", "extract_subset", "extract_subset.py"),
    os.path.join(REPO, "notebooks", "depth_occupancy", "depth_occupancy.py"),
    os.path.join(
        REPO, "notebooks", "depth_occupancy_multizone", "depth_occupancy_multizone.py"
    ),
    os.path.join(REPO, "notebooks", "train_corn", "train_corn.py"),
]


def inline_module(name: str) -> str:
    """Module source with __future__ imports, relative imports and the
    docstring removed, so it can be concatenated into one flat file."""
    path = os.path.join(SRC, f"{name}.py")
    with open(path, encoding="utf-8") as fh:
        source = fh.read()
    tree = ast.parse(source)
    lines = source.splitlines()
    drop: set[int] = set()

    body = tree.body
    if (
        body
        and isinstance(body[0], ast.Expr)
        and isinstance(body[0].value, ast.Constant)
        and isinstance(body[0].value.value, str)
    ):
        drop.update(range(body[0].lineno, (body[0].end_lineno or body[0].lineno) + 1))

    for node in body:
        if isinstance(node, ast.ImportFrom) and (
            node.module == "__future__" or (node.level or 0) > 0
        ):
            drop.update(range(node.lineno, (node.end_lineno or node.lineno) + 1))

    kept = [ln for i, ln in enumerate(lines, 1) if i not in drop]
    return "\n".join(kept).strip("\n")


def render_block(modules: list[str]) -> str:
    parts = [
        f"{BEGIN} {', '.join(modules)}",
        "# GENERATED by development/scripts/build_kernels.py from development/src/sanas/ - do not edit here.",
        "# Edit the module in development/src/sanas/, then re-run the generator.",
    ]
    for name in modules:
        parts.append("")
        parts.append(
            f"# ---- development/src/sanas/{name}.py " + "-" * max(0, 48 - len(name))
        )
        parts.append(inline_module(name))
    parts.append("")
    parts.append(END)
    return "\n".join(parts)


def process(path: str) -> tuple[bool, str]:
    """Return (changed, message) for one kernel file."""
    if not os.path.exists(path):
        return False, f"MISSING {path}"
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    lines = text.splitlines()

    begin_i = end_i = None
    for i, ln in enumerate(lines):
        if ln.startswith(BEGIN):
            begin_i = i
        elif ln.strip() == END and begin_i is not None and end_i is None:
            end_i = i
    if begin_i is None or end_i is None:
        return False, f"no vendor markers in {os.path.relpath(path, REPO)}"

    modules = [m.strip() for m in lines[begin_i][len(BEGIN) :].split(",") if m.strip()]
    block = render_block(modules)
    new_text = (
        "\n".join(lines[:begin_i] + block.splitlines() + lines[end_i + 1 :]) + "\n"
    )

    rel = os.path.relpath(path, REPO)
    if new_text == text:
        return False, f"up to date  {rel}  [{', '.join(modules)}]"
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(new_text)
    return True, f"REGENERATED {rel}  [{', '.join(modules)}]"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check", action="store_true", help="exit non-zero if anything was stale"
    )
    args = ap.parse_args()

    changed_any = False
    for path in KERNELS:
        changed, msg = process(path)
        changed_any = changed_any or changed
        print(msg)

    if args.check and changed_any:
        print(
            "\nDRIFT: kernels were out of date with development/src/sanas/. They have been "
            "regenerated; re-run --check to confirm, and do not push stale kernels.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
